packages/runtime/src/__tests__/base64.test.ts, packages/runtime/src/isolate/runtime.ts, packages/runtime/src/runtime/base64.ts
Adds support for `atob` and `btoa` APIs (https://github.com/lagonapp/serverless/issues/10)
=> feat(runtime): add base64 APIs

.github/workflows/ci.yml, packages/runtime/package.json, packages/runtime/src/__tests__/fetch.test.ts, packages/runtime/src/fetch/index.ts, packages/runtime/src/isolate/runtime.ts, packages/runtime/src/runtime/Request.ts, packages/runtime/src/runtime/Response.ts, packages/runtime/src/runtime/fetch.ts, packages/runtime/src/runtime/parseMultipart.ts, packages/types/generate.mjs, packages/types/types.d.ts
Closes #30 
Add tests for this new `Headers` API, convert usage of `headers` in `Request` and `Response` and update the runtime building strategy.
=> feat(runtime): add Headers API

packages/runtime/src/isolate/index.ts
Add `filename` to the running isolate, for better stack trace debugging.
=> feat(runtime): add filename

packages/website/global.d.ts, packages/website/lib/Layout.tsx, packages/website/lib/hooks/useTokens.ts, packages/website/lib/trpc/accountsRouter.ts, packages/website/lib/trpc/tokensRouter.ts, packages/website/pages/api/trpc/[trpc].ts, packages/website/pages/profile.tsx
Add profile page on the website, accessible from the menu:
Update name / email:
List and delete your tokens:
Delete account:
=> feat(website): add profile page

.github/workflows/ci.yml
- Add a typecheck job to run `tsc`
- Remove matrix to only use Node.js 16
- Run ci on push to main along with all pull requests
=> chore(ci): add typecheck job

.gitignore, examples/fetch-api/index.ts, examples/fetch-api/package.json, examples/preact-ssr/index.tsx, examples/preact-ssr/package.json, examples/react-ssr/index.tsx, examples/react-ssr/package.json, examples/reply-with-html/index.ts, examples/reply-with-html/package.json, examples/reply-with-json/index.ts, examples/reply-with-json/package.json, packages/cli/src/utils/deployments.ts, packages/runtime/src/fetch/index.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Add `examples` directory with examples for:
- how to reply HTML (`reply-with-html`)
- how to reply JSON (`reply-with-json`)
- how to fetch an API (`fetch-api`)
- how to do server side rendering with preact (`preact-ssr`)
- how to do server side rendering with react (`react-ssr`)
More examples will be added in the future.
=> chore: add examples directory

packages/serverless/package.json, packages/serverless/src/clickhouse.ts, packages/serverless/src/deployments/result.ts, packages/serverless/src/master.ts, packages/serverless/src/worker.ts
Move clickhouse queries to a separate worker thread, and batch queries instead of running one per function result.
=> refactor(serverless): better performance for functions results

package.json
By enabling corepack in Vercel, it can resolve the right PNPM version: https://twitter.com/tomlienard/status/1545699761570942976
=> chore: bring back pinned pnpm version

packages/cli/package.json, packages/prisma/migrations/20220709142006_remove_memory_from_stats/migration.sql, packages/prisma/schema.prisma, packages/runtime/package.json, packages/runtime/src/deployments/index.ts, packages/serverless/package.json, packages/serverless/src/__tests__/errors.test.ts, packages/serverless/src/deployments/result.ts, packages/serverless/src/exporter.ts, packages/serverless/src/master.ts, packages/serverless/src/server.ts, packages/serverless/src/worker.ts, packages/website/lib/pages/function/FunctionOverview.tsx, packages/website/lib/trpc/functionsRouter.ts, pnpm-lock.yaml
Fix memory leaks from undeploy / cache cleared deployments. Also remove memory from stats as it's not precise at all.
=> fix(serverless): memory leaks & remove memory from stats

packages/runtime/src/__tests__/eval.test.ts, packages/runtime/src/isolate/index.ts, packages/runtime/src/isolate/runtime.ts
Closes #14 
It would be a lot safer to disable code generation in `isolated-vm`, but it's currently allowed to run:
https://github.com/laverdet/isolated-vm/blob/195ae83f3e99310a7a6a190bccfe81272d56ac68/src/isolate/environment.cc#L141
=> feat(runtime): disable code evaluation

.github/workflows/ci.yml, packages/cli/src/commands/dev.ts, packages/cli/src/commands/login.ts, packages/cli/src/utils/deployments.ts, packages/cli/tsconfig.json, turbo.json
- Fix type errors in `@lagon/cli`, mostly due to trpc `AppRouter` type that wasn't working
- Remove `|| true` to typechek job
=> fix(cli): type errors

.changeset/soft-terms-perform.md, .changeset/two-ghosts-pay.md, packages/cli/src/commands/dev.ts, packages/cli/src/utils/constants.ts, packages/serverless/src/server.ts
Fix regression of #85 that caused an error when `response` is not a string, but not a `Readable` (e.g `null`, an array...)
=> fix(serverless,cli): error on non-streamed response

.changeset/long-lobsters-look.md, packages/cli/src/cli.ts, packages/cli/src/commands/deploy.ts, packages/cli/src/commands/dev.ts, packages/cli/src/utils/deployments.ts, packages/cli/src/utils/index.ts, packages/cli/src/utils/logger.ts
Add `--client <file>` option to `dev` and `deploy` commands to replace `--preact`.
Previously, `--preact` allowed to bundle an `App.tsx` file as a client file (similar to if it was bundled and placed inside the public folder), and it was hard-coded. Now, you can pass any file to `--client` and it will be bundled and available as an asset, with the name of the file + `.js` and in lowercase.
=> feat(cli): rename `--preact` to `--client <file>`

packages/serverless/src/__tests__/errors.test.ts
Increase timeout for memory full test to prevent GH action timeouts (e.g https://github.com/lagonapp/lagon/runs/7753463848?check_suite_focus=true)
=> test(serverless): increase timeout for memory full

.changeset/modern-islands-join.md, packages/cli/src/commands/dev.ts, packages/serverless/src/server.ts
Always transform `body` to a string, because fastify can give us an object if we post JSON for example.
=> fix(serverless,cli): always transform the body to a string

.changeset/fast-poets-wash.md, packages/serverless/src/deployments/index.ts
Fix a bug where the server would crash if assets were nested in folders.
=> fix(serverless): create folders in assets that are nested

packages/serverless/.env.example, packages/website/pages/api/auth/[...nextauth].ts, packages/website/pages/api/trpc/[trpc].ts
Use `unstable_getServerSession` from [nextauth](https://next-auth.js.org/configuration/nextjs#unstable_getserversession) to reduce API calls duration by not fetching the session at every authenticated request.
The API is experimental but seems to work well.
=> feat(website): use `unstable_getServerSession` to reduce API calls duration

packages/website/pages/playground/[functionId].tsx
Fix a crash on playground page due to undefined being passed to a locale param.
=> fix(website): crash on playground page

.changeset/beige-stingrays-report.md, packages/cli/src/commands/deploy.rs, packages/cli/src/commands/dev.rs, packages/cli/src/commands/login.rs, packages/cli/src/commands/logout.rs, packages/cli/src/main.rs, packages/cli/src/utils/deployments.rs
Show help when no subcommand is provided. Also, apply clippy suggestions.
=> fix(cli): show help when no subcommand provided

.changeset/spotty-experts-whisper.md, .changeset/thin-vans-complain.md, Cargo.lock, examples/preact-ssr/index.tsx, examples/preact/index.tsx, examples/react-ssr/index.tsx, examples/react/index.tsx, packages/cli/Cargo.toml, packages/cli/src/commands/build.rs, packages/cli/src/utils/deployments.rs, packages/serverless/src/deployments/filesystem.rs, packages/serverless/src/deployments/mod.rs, packages/serverless/src/main.rs, packages/website/pages/api/deployment.ts
Assets in the `public` folder (or the public folder specified using `-p`) weren't bundled and deployed.
This PR bundle all assets and:
- Outputs them in `.lagon` when using `lagon build`
- Send them to the API with the correct MIME type
Then, serverless correctly handles all assets, which are all prefixed by `public/`.
=> fix(cli,serverless): correctly bundle and deploy assets

.changeset/violet-insects-wink.md, packages/js-runtime/src/index.ts, packages/js-runtime/src/runtime/Response.ts, packages/runtime/src/http/mod.rs, packages/runtime/src/isolate/bindings/fetch.rs, packages/runtime/src/runtime/mod.rs, packages/runtime/tests/runtime.rs, packages/serverless/src/deployments/assets.rs
Handle `Uint8Array` in `Response` body.
Replace `Response` struct body from `String` to `Vec<u8>` to reply with assets that aren't utf8 (`fs::read_to_string` -> `fs::read`).
=> feat(runtime,js-runtime): handle `Uint8Array` in `Response` body

.changeset/gorgeous-lemons-wonder.md, Cargo.lock, packages/runtime/Cargo.toml, packages/runtime/src/isolate/mod.rs, packages/runtime/tests/runtime.rs, packages/serverless/src/main.rs
Implement a very very basic event loop that:
- Pumps the message loop
- Runs microtasks
- Check if the isolate has been terminated (for CPU timeout / too much memory)
- Check the state of the handler's promise and repeat until it resolves / rejected
=> feat(runtime): implement event loop

Cargo.lock, packages/runtime/Cargo.toml, packages/runtime/src/isolate/bindings/fetch.rs, packages/runtime/src/isolate/bindings/mod.rs, packages/runtime/src/isolate/mod.rs, packages/runtime/tests/runtime.rs
Properly implement Rust -> JS async bindings (using promises) polling in the event-loop.
Previously, each async binding would block its function, but now they are pooled when the event-loop ticks.
Also, replace `tokio::sync::oneshot` with `flume` to get `Copy` sender (which is still used once) and allows to not `take()` and consume the `handler_result`, which would cause infinite hanging when the returned promise state isn't `PromiseState::Ready` at the first event-loop tick.
=> refactor(runtime): proper Rust -> JS promises through the event-loop

.changeset/kind-peas-sort.md, packages/website/lib/trpc/deploymentsRouter.ts
Fix a bug when website send deployment information, where `domains` wasn't an array of string but an array of `Domain`
=> fix(website): deployments creation domains array

.changeset/proud-pants-smell.md, packages/serverless/src/deployments/filesystem.rs
Fix a bug where the assets folder wasn't deleted on undeploys, because we used `fs::rm_dir` instead of `fs::rm_dir_all`. The former only rm if the directory is empty, but we don't care and always want to delete the whole directory.
=> fix(serverless): assets directory not deleting on undeploys

.changeset/fuzzy-panthers-sin.md, packages/cli/src/utils/deployments.rs, packages/runtime/src/isolate/mod.rs, packages/runtime/tests/errors.rs
Beautify errors:
- Add the line for all runtime errors, if available
- Output esbuild errors for cli
=> feat(cli,runtime): beautify errors

.changeset/afraid-llamas-divide.md, .changeset/rotten-turkeys-tan.md, packages/cli/npm/getBinary.js, packages/cli/npm/install.js, packages/cli/npm/run.js, packages/cli/npm/uninstall.js
- Fix binary name on WIndows (add `.exe`)
- Correctly install the CLI before executing it
=> fix(cli): binary name on Windows & correctly install

.changeset/popular-comics-smile.md, packages/cli/src/commands/login.rs, packages/cli/src/utils/config.rs, packages/cli/src/utils/mod.rs
Open the configured URL on login.
=> fix(cli): open the correct URL on login

.changeset/bright-peas-rule.md, .changeset/selfish-rivers-yell.md, packages/cli/Cargo.toml, packages/cli/src/commands/dev.rs, packages/runtime/src/http/mod.rs, packages/runtime/src/isolate/bindings/pull_stream.rs, packages/serverless/Cargo.toml, packages/serverless/src/main.rs
Fix a bug with response streaming. The response channel is now unbounded to send the initial response as soon as possible.
=> fix(runtime,serverless,cli): response streaming bug

.changeset/eighty-moons-hunt.md, packages/js-runtime/src/runtime/fetch.ts, packages/runtime/src/http/request.rs, packages/runtime/src/isolate/bindings/fetch.rs, packages/runtime/src/isolate/bindings/mod.rs, packages/runtime/src/isolate/mod.rs, packages/runtime/tests/fetch.rs
Closes #200 
Handle `fetch` errors by rejecting the JS promise with the error. Also add tests.
=> feat(runtime): handle `fetch` errors

.changeset/small-pillows-lick.md, Cargo.lock, examples/satori/index.tsx, examples/satori/package.json, packages/cli/src/utils/deployments.rs, packages/js-runtime/src/index.ts, packages/js-runtime/src/runtime/Response.ts, packages/js-runtime/src/runtime/encoding.ts, packages/runtime/Cargo.toml, packages/runtime/src/http/response.rs, packages/runtime/src/isolate/mod.rs, packages/runtime/tests/fetch.rs, pnpm-lock.yaml
Add [Satori](https://github.com/vercel/satori) example. Required a few changes:
### CLI
- Add esbuild binary loader for `.wasm`
### Runtime
- Response body is converted to `Uint8Array` instead of trying to parse to a UTF string, which might fail
- Drop the isolate state when possible after cloning global
### JS Runtime
- Response body is now a `string | ArrayBuffer`
- Add the `arrayBuffer()` method on Response
=> feat(runtime,js-runtime,cli,examples): add Satori example

.changeset/fresh-pots-travel.md, packages/js-runtime/src/__tests__/console.test.ts, packages/js-runtime/src/runtime/console.ts
Following Node.js [`util.format`](https://nodejs.org/api/util.html#utilformatformat-args) (which is used behind the scene for `console.*`), this PR implements almost the same behavior, except:
- `%j`, `%o`, `%O` all fallbacks to `JSON.stringify()`
- '%c' is completely ignored
Also add tests to cover the new cases.
=> feat(js-runtime): printf-like formatting for `console.*`

.changeset/funny-rivers-sip.md, Cargo.lock, packages/cli/Cargo.toml, packages/cli/src/commands/dev.rs, packages/cli/src/main.rs
Closes #208 
Add `--env` / `-e` option to load an environment variables file when running the dev server.
=> feat(cli): add env option to dev command

.changeset/kind-boats-attack.md, packages/cli/src/commands/dev.rs, packages/runtime/src/http/request.rs, packages/serverless/src/main.rs
Closes #209 
Forward client IP address through `X-Forwarded-For` header for both CLI and serverless.
Example:
```ts
export function handler(request: Request): Response {
return new Response('My IP is: ' + request.headers.get('X-Forwarded-For'));
}
```
=> feat(cli,serverless): forward client IP through `X-Forwarded-For` header

.changeset/angry-fans-live.md, Cargo.lock, packages/serverless/Cargo.toml, packages/serverless/src/logger.rs, packages/serverless/src/main.rs
Hey everyone, this project looks exciting! I've noticed you're using Axiom so I fixed the logger for you, hope that's alright 😊 
This PR fixes a bug where only the first log event would've been sent to Axiom. 
Instead of grabbing the first value from the receiver, it turns the receiver into an async stream and passes it to `ingest_stream` for ingestion.
There's more things that can be improved (e.g. `ingest_stream` should log errors and restart instead of panicking on error) but this is meant to be a first step.
It also changes the way Axiom is detected to using the client constructor which will automatically configure from environment variables.
And it renames the `timestamp` field name to `_time` so it's properly detected by Axiom.
Please let me know if you have any questions regarding …
=> fix(serverless): Axiom logger

.changeset/few-foxes-cheat.md, .changeset/tender-walls-tap.md, Cargo.lock, packages/runtime/src/isolate/mod.rs, packages/serverless/.env.example, packages/serverless/Cargo.toml, packages/serverless/src/main.rs
Add configurable LRU time cache (aka [TLRU](https://en.wikipedia.org/wiki/Cache_replacement_policies#Time_aware_least_recently_used_(TLRU))) for isolates. It's configurable via the `LAGON_ISOLATES_CACHE_SECONDS` environment variables, and is set by default to 60 seconds for development.
=> feat(serverless): add LRU time cache for isolates

.changeset/beige-ways-visit.md, packages/js-runtime/src/__tests__/fetch.test.ts, packages/js-runtime/src/runtime/Response.ts
This PR implements `new Response()` with no arguments and `new Response(null)` as required [by the spec](https://fetch.spec.whatwg.org/#ref-for-dom-response%E2%91%A0) and adds a few tests for the Response constructor.
=> fix(js-runtime): allow no-args constructor for Response

.changeset/afraid-fireants-flash.md, packages/js-runtime/src/__tests__/url.test.ts, packages/js-runtime/src/runtime/URL.ts
This PR appends a port number to the `origin` property of the `URL` class when using a non-default port number and adds a test case for it.
=> fix(js-runtime): include non-default port in URL's origin property

.changeset/short-scissors-explode.md, packages/serverless/src/deployments/assets.rs, packages/serverless/src/deployments/filesystem.rs, packages/serverless/src/deployments/mod.rs, packages/serverless/src/deployments/pubsub.rs, packages/serverless/src/logger.rs, packages/serverless/src/main.rs
Improve error handling for serverless, following #236 and #235.
=> refactor(serverless): better error handling

.changeset/flat-nails-hunt.md, Cargo.lock, packages/serverless/Cargo.toml, packages/serverless/src/deployments/filesystem.rs, packages/serverless/src/deployments/mod.rs, packages/serverless/src/deployments/pubsub.rs, packages/serverless/src/logger.rs, packages/serverless/src/main.rs
Add more context to logs using the [KV feature of log](https://docs.rs/log/latest/log/kv/index.html). This allows us to pass context like deployment id, request... to logs, and transfer them to Axiom.
=> refactor(serverless): add more context to logs

.changeset/purple-sloths-share.md, packages/website/locales/fr.ts
Fix a typo for "déploiement" (was "déploiment" before, which means deployment) in the french locale of the website.
=> fix(website): typo for "déploiement" in french locale

.changeset/mighty-turkeys-joke.md, .changeset/polite-ducks-scream.md, packages/cli/src/commands/dev.rs, packages/cli/src/utils/deployments.rs, packages/runtime/src/isolate/bindings/fetch.rs, packages/runtime/src/isolate/bindings/pull_stream.rs, packages/runtime/src/isolate/mod.rs, packages/runtime/src/runtime/mod.rs, packages/runtime/tests/errors.rs, packages/runtime/tests/fetch.rs, packages/runtime/tests/promises.rs, packages/runtime/tests/runtime.rs, packages/runtime/tests/streams.rs, packages/serverless/src/main.rs
- Add back functions statistics
- Properly timeout and terminate long-running functions.
=> refactor(runtime,serverless): add functions statistics and fix timeout

.changeset/rude-days-help.md, packages/cli/src/commands/dev.rs, packages/serverless/src/main.rs
Closes #232
Previously, static files were only served when the URL matched the file path. That causes issues for many frameworks, that rely on a `foo.html` to serve the `/foo` URL, or `bar/index.html` to serve the `/bar` URL.
The two above paths are now supported for both CLI and serverless, and allow to serve HTML files without having the extension (`.html`) in the URL.
=> feat(serverless,cli): Support .html and index.html for static file paths

packages/js-runtime/src/index.ts, packages/js-runtime/src/runtime/http/Request.ts, packages/js-runtime/src/runtime/http/Response.ts, packages/js-runtime/src/runtime/http/body.ts, packages/runtime/tests/runtime.rs
Since #240, performances were degraded a lot due to huge objects being allocated at each function call. Now, `Request/Response`'s `body` can be a `string` instead of always being a `ReadableStream` when it's not needed.
https://twitter.com/tomlienard/status/1592209845155164161
=> perf(js-runtime): more lazy Request/Response

.changeset/eighty-moons-smoke.md, packages/serverless/src/deployments/assets.rs, packages/serverless/src/deployments/mod.rs, packages/serverless/src/deployments/pubsub.rs, packages/serverless/src/main.rs
Improve performances by avoiding expensive clones, mostly on `Deployment` by using an `Arc`.
=> perf(serverless): avoid expensive clones

.changeset/honest-seals-grab.md, packages/js-runtime/src/__tests__/fetch.test.ts, packages/js-runtime/src/index.ts, packages/js-runtime/src/runtime/http/Headers.ts, packages/js-runtime/src/runtime/http/body.ts, packages/js-runtime/src/runtime/http/fetch.ts, packages/runtime/src/http/request.rs, packages/runtime/src/http/response.rs
Use shorter keys for Request/Response Rust <-> JS conversion.
=> perf(runtime): use shorter keys for Request/Response

.changeset/calm-cougars-appear.md, packages/js-runtime/src/__tests__/formData.test.ts, packages/js-runtime/src/__tests__/url.test.ts, packages/js-runtime/src/runtime/core.ts, packages/js-runtime/src/runtime/http/URLSearchParams.ts
Add support for `application/x-www-form-urlencoded` in Request/Response `formData()`, using the existing `URLSearchParams` API.
Initially raised on Twitter:
https://twitter.com/cyco130/status/1591876005735563265
=> feat(js-runtime): support `application/x-www-form-urlencoded` in Request/Response `formData()`

.changeset/fast-yaks-tie.md, packages/cli/src/commands/deploy.rs, packages/cli/src/commands/rm.rs, packages/cli/src/main.rs, packages/cli/src/utils/deployments.rs
Relates to #268 
Allow having multiple Functions in a folder by renaming `.lagon/config.json` to `.lagon/<filename>.json`
=> feat(cli): allow having multiple functions in a folder

.changeset/twelve-rats-dance.md, packages/cli/src/commands/deploy.rs, packages/cli/src/commands/link.rs, packages/cli/src/commands/mod.rs, packages/cli/src/main.rs
Relates to #268 
Add `lagon link` command to link a local Function to an already deployed Function.
=> feat(cli): add `lagon link` command

.changeset/wild-cups-care.md, packages/runtime/src/isolate/mod.rs
Fix functions timeout not working properly in serverless (but working fine in runtime).
This is because serverless uses a `LocalPoolHandle` to always execute an isolate on the same thread while allowing to have multiple threads to run a pool of isolate. Using `tokio::task::spawn`, the timeout future is spawned on the same thread as the isolate, and will be blocked when the isolate blocks (e.g long script parsing, infinite loops...).
The solution is to use a `tokio::task::spawn_blocking` to spawn the timeout future on another thread where we can block.
=> fix(serverless): functions timeout

.changeset/gold-pans-greet.md, packages/dashboard/lib/api/deployments.ts, packages/dashboard/lib/constants.ts, packages/dashboard/lib/trpc/deploymentsRouter.ts, packages/dashboard/lib/trpc/functionsRouter.ts, packages/dashboard/lib/trpc/organizationsRouter.ts, packages/dashboard/prisma/migrations/20221125172950_add_startup_timeout_to_function/migration.sql, packages/dashboard/prisma/schema.prisma, packages/runtime/src/isolate/mod.rs, packages/serverless/src/deployments/mod.rs, packages/serverless/src/deployments/pubsub.rs, packages/serverless/src/main.rs
Closes #277 
Add a new `startupTimeout` option to functions, which is different from `timeout`. When instantiating/evaluating large scripts, the timeout might be reached, even if executing the code itself wouldn't reach the timeout. So we introduce a larger `startupTimeout`, only when the isolate hasn't been created.
=> feat(runtime,serverless,dashboard): add isolates startup timeout

.changeset/real-ladybugs-scream.md, packages/runtime/src/isolate/bindings/crypto/decrypt.rs, packages/runtime/src/isolate/bindings/crypto/digest.rs, packages/runtime/src/isolate/bindings/crypto/encrypt.rs, packages/runtime/src/isolate/bindings/crypto/mod.rs, packages/runtime/src/isolate/bindings/crypto/sign.rs, packages/runtime/src/isolate/bindings/crypto/verify.rs, packages/runtime/src/isolate/bindings/fetch.rs, packages/runtime/src/isolate/bindings/mod.rs
Use two macros for Rust <-> JS bindings, instead of duplicating code (particularly with async bindings).
Now you can use
- `binding!()` for sync bindings, that take the same binding function as before
- `async_binding!()` for async bindings, which take a function to return the parsed args, and a second function that is async and returns a `PromiseResult`. This last function is basically the future we created before.
=> refactor(runtime): use macros for Rust <-> JS bindings

.changeset/funny-peaches-tie.md, Cargo.lock, packages/runtime/Cargo.toml, packages/runtime/src/isolate/mod.rs, packages/runtime/src/runtime/mod.rs
Instead of using `spawn_blocking` which spawns a dedicated blocking thread (until the default limit of 512) to run the task, we can use a `LocalPoolHandle` of size 1 to always run the timeout futures on the same thread.
=> perf(serverless): don't spawn a thread on each request

.changeset/dry-mangos-allow.md, .changeset/sweet-kids-flash.md, packages/cli/src/commands/promote.rs, packages/cli/src/commands/rm.rs, packages/cli/src/commands/undeploy.rs, packages/cli/src/utils/trpc.rs, packages/dashboard/lib/api/deployments.ts, packages/dashboard/lib/trpc/accountsRouter.ts, packages/dashboard/lib/trpc/deploymentsRouter.ts, packages/dashboard/lib/trpc/functionsRouter.ts, packages/dashboard/lib/trpc/organizationsRouter.ts, packages/dashboard/lib/trpc/tokensRouter.ts
- Allow promoting deployments when a function doesn't have any production deployment
- Always return data for tRPC to fix a bug in CLI while parsing empty responses
=> fix(cli,dashboard): promote deployments without existing production deployments

.github/workflows/cd.yml
Trigger the CD workflow when the `Release` workflow is `completed` to upload the artifacts to the created release.
=> ci: publish assets on release

.changeset/bright-spoons-switch.md, packages/dashboard/lib/trpc/functionsRouter.ts
Use `query` instead of `queryLegacy` for axiom logs, using an apl query string.
=> fix(dashboard): use `query` instead of `queryLegacy` for axiom

.changeset/green-flowers-cross.md, docker/serverless.Dockerfile, packages/serverless/src/deployments/cache.rs, packages/serverless/src/deployments/mod.rs, packages/serverless/src/deployments/pubsub.rs, packages/serverless/src/logger.rs, packages/serverless/src/main.rs
- Only load a `.env` file on debug builds.
- Expose the prometheus port on the Dockerfile (9000)
=> fix(serverless): don't use a .env file on release

.changeset/nice-dogs-divide.md, packages/serverless/src/deployments/pubsub.rs, packages/serverless/src/logger.rs, packages/serverless/src/main.rs
- Add more metrics:
- `lagon_deployments`
- `lagon_undeployments`
- `lagon_promotion`
- `lagon_bytes_out`
- `lagon_ignored_requests`
- Add the region as a label in all metrics
=> feat(serverless): add more metrics

.github/workflows/cd.yml
Upload assets from CD to the latest release on `workflow_run`
=> ci: upload to release on workflow_run

.changeset/honest-sheep-perform.md, packages/docs/pages/cli.mdx
Fix the position of `lagon link` section that was inside the `self-hosting configuration` section instead of inside `usage`
=> fix(docs): position of `lagon link` section

.changeset/spotty-wombats-bathe.md, .changeset/wise-cooks-warn.md, packages/runtime/tests/disallow_codegen.rs, packages/serverless/src/main.rs
Closes #330
- Forward the `X-Real-Ip` header as `X-Forwarded-For` (or fallback to the remote addr IP if the header is not found)
- Add a new `X-Lagon-Region` header
=> feat(serverless): forward `X-Real-Ip` as `X-Forwarded-For` & `X-Lagon-Region`

.changeset/breezy-guests-nail.md, packages/runtime/Cargo.toml, packages/runtime/src/isolate/bindings/fetch.rs
Hoist the HTTP(S) client using `lazy_static` to avoid creating and allocating a new client on each `fetch` binding call.
=> perf(runtime): avoid creating a new HTTP(S) client on each `fetch` call

packages/js-runtime/src/index.ts, packages/runtime/tests/errors.rs
Throw an error if `handler` is not a function. Add 2 tests in `runtime` to test this behavior.
=> test(runtime): throw error if `handler` is not a function

.changeset/clever-ears-juggle.md, packages/dashboard/lib/trpc/statsRouter.ts, packages/serverless/src/main.rs
Add new metrics for other types of responses (errors, timeouts, memory limits) in serverless
=> feat(serverless): add metrics for errors/timeouts/memory limits

.changeset/giant-cats-mate.md, packages/js-runtime/src/__tests__/url.test.ts, packages/js-runtime/src/runtime/http/URL.ts
This PR brings the `URL` class closer to the standard. In particular it adds the ability to reflect the changes to the `href` property when a part is updated: e.g. when `searchParams.set` is called.
=> fix(js-runtime): bring URL closer to the standard

.changeset/weak-windows-remain.md, packages/dashboard/lib/api/deployments.ts, packages/dashboard/lib/trpc/functionsRouter.ts
Closes #380 
When we update a function setting (function name, cron, cron region, domains, environment variables), the current production deployment is automatically redeployed.
=> feat(dashboard): redeploy production deployment when a setting is updated

.changeset/config.json, .changeset/tricky-dogs-impress.md, packages/docs/pages/runtime-apis.mdx, packages/js-runtime/package.json, packages/js-runtime/src/index.ts, packages/js-runtime/src/runtime/global/navigator.ts
Add the `navigator` global with a single field `userAgent` as [defined in WinterCG](https://proposal-common-min-api.deno.dev/#requirements-for-navigatoruseragent).
Also, set `@lagon/runtime` & `@lagon/js-runtime` as fixed packages in changeset config, to always keep the same version since they depend on each other.
=> feat(js-runtime,docs): add `navigator.userAgent` API

.changeset/dull-flies-compare.md, packages/runtime/src/isolate/bindings/console.rs, packages/runtime/src/isolate/mod.rs, packages/serverless/src/deployments/cache.rs, packages/serverless/src/main.rs
Wrap the `metadata` of an isolate inside an `Rc` to avoid cloning the tuple many times.
=> perf(runtime,serverless): use an `Rc` for isolates metadata instead of cloning

.changeset/silly-ligers-flash.md, .gitmodules, packages/docs/pages/runtime-apis.mdx, packages/js-runtime/package.json, packages/js-runtime/src/__tests__/blob.test.ts, packages/js-runtime/src/__tests__/file.test.ts, packages/js-runtime/src/index.ts, packages/js-runtime/src/runtime/blob.ts, packages/js-runtime/src/runtime/file.ts, packages/js-runtime/tsconfig.json, packages/runtime/src/runtime/mod.rs, packages/wpt-runner/src/main.rs, pnpm-lock.yaml, vitest.config.mts
The current `Blob` implementation (from [blob-polyfill](https://www.npmjs.com/package/blob-polyfill)) causes issues because it uses `document`. The CI didn't catch the bug before: https://github.com/lagonapp/lagon/pull/253#issuecomment-1356360719, maybe due to a wrong caching mechanism.
Initial WPT results:
=> feat(js-runtime): new `Blob` & `File` implementations

.changeset/thirty-spiders-glow.md, Cargo.lock, packages/docs/pages/runtime-apis.mdx, packages/runtime/Cargo.toml, packages/runtime/src/isolate/bindings/crypto/digest.rs, packages/runtime/tests/crypto.rs
Closes #400
Relates to https://github.com/honojs/hono/issues/734#issuecomment-1359246312
Add SHA1 to the supported algorithms of `CryptoSubtle#digest`
=> feat(runtime): add SHA1 to `CryptoSubtle#digest`

.changeset/light-tomatoes-bake.md, Cargo.lock, packages/cli/Cargo.toml, packages/cli/src/commands/dev.rs
Fix random segfault errors when using `lagon dev`:
When calling into V8 to resolve Rust Futures to JS Promises while using another thread (from the HTTP server) than the previous one, V8 crashed:
```
[1]    6212 segmentation fault  cargo run -- dev test.ts
```
The full stacktrace:
```
(lldb) bt
* thread #8, name = 'tokio-runtime-worker', stop reason = EXC_BAD_ACCESS (code=1, address=0xf5d0)
* frame #0: 0x00000001005fce24 lagon-cli`::main_thread_local_heap() at isolate.cc:5868:10 [opt]
frame #1: 0x0000000100751eec lagon-cli`::BytecodeArrayIterator() at bytecode-array-iterator.cc:28:45 [opt]
frame #2: 0x000000010051cdc8 lagon-cli`::BaselineCompiler() at baseline-compiler.cc:288:7 [opt]
frame #3: 0x00000001005344f4 lagon-cli`::GenerateBaselineCode() at baseline.cc:64:30 [opt]
frame #4: …
```
=> fix(cli): random segfault with `lagon dev`

.changeset/nervous-cooks-promise.md, Cargo.lock, packages/runtime/Cargo.toml, packages/runtime/src/crypto.rs, packages/runtime/src/isolate/bindings/crypto/decrypt.rs, packages/runtime/src/isolate/bindings/crypto/encrypt.rs, packages/runtime/src/isolate/bindings/crypto/random_values.rs, packages/runtime/tests/crypto.rs
The AES-GCM algorithm should use 16 bytes iv, but used the default (from the crate) of 12 bytes before. This is required by the [W3C spec](https://w3c.github.io/webcrypto/#aes-cbc-operations): 
> If the [iv](https://w3c.github.io/webcrypto/#dfn-AesCbcParams-iv) member of normalizedAlgorithm does not have length 16 bytes, then [throw](https://webidl.spec.whatwg.org/#dfn-throw) an [OperationError](https://webidl.spec.whatwg.org/#operationerror).
Also remove a `dbg!` inside the random_value binding.
=> fix(runtime): use 16 bytes iv for AES-GCM

.changeset/heavy-kings-float.md, .changeset/hip-mails-shop.md, .changeset/rude-items-brush.md, packages/cli/src/commands/dev.rs, packages/runtime/src/isolate/mod.rs, packages/runtime/tests/disallow_codegen.rs, packages/runtime/tests/errors.rs, packages/runtime/tests/fetch.rs, packages/runtime/tests/streams.rs, packages/serverless/src/main.rs, packages/wpt-runner/src/main.rs
Closes #413
- If we returned a stream without closing it, the runtime would hang indefinitely without shutting down after the execution timeout elapsed. Resolved by moving the `termination_rx` check before the streaming status checks inside the event loop
- The runtime didn't catch promises rejection because we didn't have a `promise_reject_callback` handler. Resolved by adding this callback, adding a new `promise_rejected_message` to the Isolate state, and checking for its presence inside the event loop
- Close the stream on CLI on Serverless when we receive a result that isn't part of the stream
=> fix(runtime,serverless,cli): properly handle errors and timeouts while streaming

.changeset/popular-apricots-shake.md, packages/js-runtime/src/runtime/http/Response.ts, packages/wpt-runner/current-results.md
Closes #419
Fix the implementation of the static `Response.json()` method. 100% conformance with web-platform-tests `response-static-json.any.js` test
=> fix(js-runtime): `Response.json()` API conformance with WPT

.changeset/ten-hats-sell.md, .changeset/tricky-cups-decide.md, packages/cli/src/utils/deployments.rs
- Bundle in ESNext instead of ES2020
- Add support for `exports` key of `lagon` using `--conditions`
- Define `process.env.NODE_ENV` to `"production"` so ESBuild can tree shake libraries like React
=> fix(cli): define `process.env.NODE_ENV` to `"production"` & bundle in ESNext

.changeset/loud-clocks-tell.md, packages/js-runtime/src/index.ts, packages/js-runtime/src/runtime/http/Headers.ts, packages/js-runtime/src/runtime/http/Response.ts, packages/js-runtime/src/runtime/http/URL.ts, packages/wpt-runner/current-results.md
From:
```
1402 tests, 349 passed, 1047 failed
-> 24% conformance
```
To:
```
1402 tests, 361 passed, 1035 failed
-> 25% conformance
```
The only failing WPT test is `Check error returned when giving invalid url to redirect()`, which should be fixed automatically when our `URL` implementation throw errors on malformatted URLs.
=> fix(js-runtime): `Response.error()` & `Response.redirect()` WPT conformance

.changeset/wild-boats-shout.md, packages/cli/src/utils/deployments.rs
Globally installed packages via NPM are not runnable as-is, we need to use the full path to the `esbuild.cmd` executable.
=> fix(cli): ESBuild path on Windows

.changeset/many-beans-itch.md, package.json, packages/docs/pages/runtime-apis.mdx, packages/js-runtime/src/index.ts, packages/js-runtime/src/runtime/blob.ts, packages/js-runtime/src/runtime/event.ts, packages/js-runtime/src/runtime/streams.ts, packages/wpt-runner/current-results.md, packages/wpt-runner/src/main.rs, pnpm-lock.yaml
Closes #415 
Add `Event` & `EventTarget` APIs, as required by WinterCG. Also add `CustomEvent` API to make WPT tests pass:
```
39 tests, 34 passed, 5 failed
-> 87% conformance
```
Most of the failing tests are due to unimplemented methods and fields, that are still tested by WPT (`returnValue`, `initEvent()`)
=> feat(js-runtime): add `Event` & `EventTarget` APIs

packages/cli/src/commands/dev.rs, packages/runtime/src/isolate/callbacks.rs, packages/runtime/src/isolate/mod.rs, packages/runtime/src/isolate/options.rs, packages/runtime/src/runtime/mod.rs, packages/runtime/src/runtime/options.rs, packages/runtime/tests/allow_codegen.rs, packages/runtime/tests/crypto.rs, packages/runtime/tests/disallow_codegen.rs, packages/runtime/tests/errors.rs, packages/runtime/tests/fetch.rs, packages/runtime/tests/promises.rs, packages/runtime/tests/runtime.rs, packages/runtime/tests/streams.rs, packages/serverless/src/main.rs, packages/wpt-runner/src/main.rs
- Move option structs to separate files
- Remove `with_` prefix in builders' methods in options
- Move callbacks to a separate file
=> refactor(runtime): clean and better file architecture

.changeset/short-foxes-care.md, Cargo.lock, packages/runtime/Cargo.toml, packages/runtime/src/isolate/bindings/fetch.rs, packages/runtime/tests/fetch.rs
Closes #445
Follow redirects in `fetch()` calls for both absolute and relative URLs. There is a hard limit of 5 redirects before throwing a "redirect loop" error.
=> feat(runtime): follow redirects in `fetch()`

packages/js-runtime/src/runtime/http/URL.ts
Handbook: [Postfix !](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#non-null-assertion-operator-postfix-)
=> fix(js-runtime): use non-null assertion operator in favor of ts-expect-error

.changeset/dry-chefs-arrive.md, .changeset/shiny-moons-pump.md, crates/cli/src/commands/dev.rs, crates/runtime/tests/disallow_codegen.rs, crates/runtime/tests/errors.rs, crates/runtime/tests/fetch.rs, crates/runtime/tests/streams.rs, crates/runtime_isolate/src/callbacks.rs, crates/runtime_isolate/src/lib.rs, crates/runtime_isolate/src/options.rs
Improve errors stack trace by showing the full stack trace, in a similar format as browsers. Each frame prints the function name if it exists, and the line/column of the frame.
Also show errors in the terminal for the CLI.
=> feat(runtime): improve errors stack trace

packages/dashboard/lib/components/FunctionLinks.tsx, packages/dashboard/lib/components/LayoutTitle.tsx, packages/dashboard/lib/pages/functions/FunctionsList.tsx
Hi, really excited with this project and willing to contribute a lot.
- This PR does two little things:
1. Add bottom padding in `LayoutTitle` component: [3b97df4](https://github.com/lagonapp/lagon/commit/3b97df48a1ef8d1d646e25c226ba3abd74b0b8e0)
2. Prevent open functions' page on link click: [480d60b4](https://github.com/lagonapp/lagon/commit/480d60b4cc2d973017275eb3aa44a06e18955afa)
Currently, if you click the deployment link via functions list card (eg: `something-something.lagon.app`), it will open the deployment in new tab, but the original tab will open the deployment details. This PR fix this using `event.stopPropagation()`. [ref](https://stackoverflow.com/a/54075528)
=> fix: improve `LayoutTitle` and `FunctionLinks`

.changeset/popular-insects-dance.md, crates/runtime/tests/runtime.rs, crates/runtime_isolate/src/lib.rs
Regression of #453 
The state was borrowed every time we called `evaluate` (first request + subsequent requests) but only dropped on first requests. This PR fixes this bug by not borrowing the state at first and mutably borrowing only on the first request (which is then dropped automatically)
Added a new `execute_function_twice` test that runs a function twice. Without the fix, this test is failing.
=> fix(runtime): borrow error when calling the same function twice

.changeset/dull-geckos-protect.md, .changeset/wicked-islands-exercise.md, crates/cli/src/commands/dev.rs, crates/serverless/src/main.rs, packages/js-runtime/src/index.ts
It's possible to have a stream done before the response is sent. This was already "supported": meaning it was working fine, but wrongly assumed that it was an error.
This PR properly handle this data -> done -> start streaming flow, and also handle errors if we get data when the stream is already done.
Also simplify the js-runtime streaming handling, not sure why it used a new `ReadableStream` because it's 100% useless.
=> feat(serverless,cli): allow ending a stream before sending the response

.changeset/cuddly-mugs-play.md, Cargo.lock, crates/runtime/Cargo.toml, crates/runtime/tests/crypto.rs, crates/runtime/tests/errors.rs, crates/runtime/tests/timers.rs, crates/runtime_isolate/src/bindings/crypto/random_values.rs, crates/runtime_isolate/src/bindings/mod.rs, crates/runtime_isolate/src/bindings/queue_microtask.rs, crates/runtime_isolate/src/bindings/sleep.rs, crates/runtime_isolate/src/lib.rs, crates/runtime_v8_utils/src/lib.rs, packages/docs/pages/runtime-apis.mdx, packages/js-runtime/src/index.ts, packages/js-runtime/src/runtime/global/timers.ts
Add timers APIs (`setTimeout`, `setInterval`, `clearTimeout`, `clearInterval`, `queueMicrotask`).
Both `setTimeout` and `setInterval` uses a new `Lagon.sleep(ms)` method, that sleeps the future for the given duration.
=> feat(runtime,js-runtime): timers APIs

.changeset/moody-guests-tan.md, crates/serverless/src/main.rs, docker/Dockerfile
Use the system root CA to connect to MySQL, instead of allowing insecure connections with an invalid certificate.
See https://planetscale.com/docs/concepts/secure-connections#ca-root-configuration
=> fix(serverless): use the system root CA to connect to MySQL

crates/cli/src/commands/build.rs, crates/cli/src/commands/dev.rs, crates/cli/src/utils/config.rs, crates/runtime_crypto/src/methods/decrypt.rs, crates/runtime_crypto/src/methods/encrypt.rs, crates/runtime_crypto/src/methods/sign.rs, crates/runtime_crypto/src/methods/verify.rs, crates/runtime_isolate/src/bindings/fetch.rs, crates/runtime_isolate/src/bindings/pull_stream.rs, crates/runtime_isolate/src/callbacks.rs, crates/runtime_v8_utils/src/lib.rs, crates/serverless/src/deployments/assets.rs, crates/serverless/src/deployments/filesystem.rs
Remove most of `unwrap()` in the codebase to properly handle errors.
=> refactor(cli,runtime,serverless): clean unwrap() usage

.changeset/rich-tomatoes-protect.md, .changeset/thirty-dryers-thank.md, crates/runtime/tests/timers.rs, packages/js-runtime/src/runtime/core.ts, packages/js-runtime/src/runtime/global/timers.ts, packages/js-runtime/src/runtime/http/Request.ts
Fix timers id to always be unique
Also, add `self` to `globalThis`
Add a new test inside runtime that executes two `setTimeout` with different intervals and cancels the second one. It doesn't cancel the first one as it would before this fix.
=> fix(js-runtime): timers id are always unique

.dockerignore, docker/Dockerfile
Reduce Docker image size:
- Smaller runtime image (`debian:bullseye-slim` instead of `rust:slim-buster`)
- Use [cargo chef](https://github.com/LukeMathWalker/cargo-chef) to speed up docker builds
- Update node image to `bullseye-slim`
From **317MB** to **55.2MB**, so a 82% decrease!
=> chore: reduce docker image size

.changeset/fast-geese-help.md, crates/serverless/package.json, crates/serverless/src/deployments/cache.rs, crates/serverless/src/main.rs
An isolate must be dropped (which will call `exit()` and terminate the execution) in the same thread as it was created in.
=> fix(serverless): drop isolates in the same thread as they were created

.changeset/pretty-eagles-reply.md, crates/serverless/src/deployments/cache.rs, crates/serverless/src/deployments/pubsub.rs, crates/serverless/src/main.rs
Following #483 
The logic to drop isolates on the same thread as they were created was missing for pub/sub events (deployments, undeployments, promotions). This PR moves this logic to a function used both in the cache clear task and in the pub/sub events handling.
=> fix(serverless): always drop isolates on the same thread as created

.changeset/perfect-ladybugs-mate.md, crates/runtime/tests/fetch.rs, crates/runtime_isolate/src/bindings/fetch.rs, crates/runtime_isolate/src/bindings/mod.rs, crates/runtime_isolate/src/lib.rs, packages/docs/pages/cloud/limits.mdx
This PR complements the limit of redirections for `fetch()`, by allowing up to 20 `fetch()` calls (without redirections) per execution.
Also add a test that ensures that an error is thrown if we go beyond this limit, but that it still works in subsequent requests.
And add the `fetch()` limits to the docs.
=> feat(runtime,ui): limit the number of `fetch()` calls per execution

.changeset/witty-weeks-complain.md, packages/dashboard/lib/constants.ts, packages/docs/pages/cloud/regions.mdx
Add two new regions for a total of 14:
- `san-francisco-us-west` (San Francisco, California)
- `bangalore-ap-south` (Bangalore, India)
=> feat(dashboard,docs): add san-francisco-us-west & bangalore-ap-south regions

.changeset/plenty-seahorses-hide.md, crates/runtime/tests/fetch.rs, crates/runtime_isolate/src/lib.rs
Refactor the isolates timeout logic to use a [condvar](https://doc.rust-lang.org/stable/std/sync/struct.Condvar.html) using [`wait_timeout_while`](https://doc.rust-lang.org/stable/std/sync/struct.Condvar.html#method.wait_timeout_while). The thread waiting for the timeout is notified every time we run any pending promise, in order to stop counting the time.
=> refactor(runtime): use a condvar to timeout isolates execution

.changeset/unlucky-berries-knock.md, packages/dashboard/lib/trpc/statsRouter.ts
Fix an error on the `stats` tRPC procedure that occurred when we didn't have data for the function.
=> fix(dashboard): error on stats procedure without data

.changeset/angry-keys-bake.md, CONTRIBUTING.md, crates/cli/src/commands/dev.rs
Previously, all events from [notify-rs](https://github.com/notify-rs/notify) assumed that the dev server should be reloaded. This includes metadata changes, that we want to ignore. Now, the dev server only updates when a file's content is modified / a file is added / a file is deleted.
=> fix(cli): only update the dev server when files are added/deleted/modified

.changeset/clever-pigs-sit.md, crates/cli/src/commands/dev.rs, crates/runtime/tests/errors.rs, crates/runtime_isolate/src/lib.rs, crates/runtime_isolate/src/options.rs, crates/serverless/src/cronjob.rs, crates/serverless/src/main.rs
Store timeouts as `Duration` inside `IsolateOptions` to avoid creating new `Duration` instances every time the isolate is run.
Also increase isolate timeout for `dev` command of the CLI.
=> perf(runtime): store timeouts as `Duration`

.changeset/curvy-cameras-design.md, crates/cli/src/commands/dev.rs, crates/runtime_utils/src/response.rs, crates/serverless/src/main.rs
Send a `404` error if we request a `favicon.ico` (automatically sent by browsers) without having an asset for it.
=> fix(cli,serverless): send 404 if favicon doesn't exists

.changeset/lazy-sloths-worry.md, crates/runtime_http/src/headers.rs, crates/runtime_http/src/lib.rs, crates/runtime_http/src/request.rs, crates/serverless/src/main.rs
Trace request id in logs using a new `x-lagon-id` header. This header isn't forwarded to isolates.
=> feat(serverless): trace request id in logs

.changeset/rude-ducks-listen.md, packages/dashboard/lib/trpc/statsRouter.ts
Return the average of the CPU time for records > 0.
=> fix(dashboard): CPU time stats to return average > 0

.changeset/good-games-sing.md, crates/wpt-runner/current-results.md, crates/wpt-runner/src/main.rs, packages/docs/pages/runtime-apis.mdx, packages/js-runtime/src/runtime/http/Headers.ts
Closes #570 
Add support for [`Headers#getSetCookie()`](https://fetch.spec.whatwg.org/#dom-headers-getsetcookie).
Note that the current `Headers` implementation doesn't support ordering headers with the same key (so only `set-cookie`)
=> feat(js-runtime): add `Headers#getSetCookie()`

.changeset/heavy-llamas-arrive.md, crates/cli/src/commands/dev.rs, crates/cli/src/commands/ls.rs, crates/cli/src/utils/console.rs, crates/cli/src/utils/deployments.rs, crates/wpt-runner/src/main.rs
Improve the contrast of the colors by using `bright_black` instead of `black`:
Before:
After:
=> feat(cli): improve contrast of the colors

.changeset/early-wombats-ring.md, .changeset/healthy-rice-fly.md, .gitignore, crates/runtime/Cargo.toml, crates/runtime/package.json, crates/runtime/tests/crypto.rs, crates/runtime/tests/disallow_codegen.rs, crates/runtime/tests/errors.rs, crates/runtime/tests/fetch.rs, crates/runtime/tests/promises.rs, crates/runtime/tests/runtime.rs, crates/runtime/tests/streams.rs, crates/runtime/tests/timers.rs, crates/runtime_isolate/Cargo.toml, crates/runtime_isolate/src/bindings/mod.rs, crates/runtime_isolate/src/callbacks.rs, crates/runtime_isolate/src/lib.rs, crates/runtime_isolate/src/options.rs, crates/serverless/Cargo.toml, crates/serverless/build.rs, crates/serverless/src/main.rs, packages/js-runtime/src/__tests__/console.test.ts, packages/js-runtime/src/__tests__/crypto.test.ts, packages/js-runtime/src/__tests__/fetch.test.ts, packages/js-runtime/src/index.ts, packages/js-runtime/src/runtime/global/console.ts, packages/js-runtime/src/runtime/global/crypto.ts, packages/js-runtime/src/runtime/global/timers.ts, packages/js-runtime/src/runtime/http/fetch.ts, turbo.json
Add a `build.rs` in `crates/serverless` to generate a `snapshot.bin` file containing a V8 heap snapshot of the `js-runtime` code, which is then used when booting isolates (which only contains the user's code). It's not mandatory to use a snapshot to start a Lagon runtime, but it currently reduces the cold start by a lot. Here's a before/after running 6 times a cold start:
Before (or by not providing a V8 snapshot):
```
Statistics: IsolateStatistics { cpu_time: 5.660791ms, memory_usage: 583232 }
Statistics: IsolateStatistics { cpu_time: 3.700791ms, memory_usage: 583232 }
Statistics: IsolateStatistics { cpu_time: 3.214416ms, memory_usage: 583232 }
Statistics: IsolateStatistics { cpu_time: 2.923625ms, memory_usage: 583232 }
Statistics: IsolateStatistics { cpu_time: 3.115166ms, memory_usage: …
```
=> feat(runtime,serverless): add V8 heap snapshots

.changeset/selfish-parents-fail.md, crates/runtime_isolate/src/bindings/sleep.rs, crates/serverless/src/main.rs
Remove unused `hyper::Client` that was copied from the `fetch` binding and is useless inside the `sleep` binding.
=> fix(runtime): remove unused HTTP client

.changeset/nice-cars-build.md, crates/cli/src/commands/build.rs, crates/cli/src/commands/deploy.rs, crates/cli/src/commands/dev.rs, crates/cli/src/commands/link.rs, crates/cli/src/commands/ls.rs, crates/cli/src/commands/promote.rs, crates/cli/src/commands/rm.rs, crates/cli/src/commands/undeploy.rs, crates/cli/src/main.rs, crates/cli/src/utils/deployments.rs, crates/cli/src/utils/mod.rs, packages/docs/pages/cli.mdx
Improve functions configuration by saving parameters into a local config file.
When using `lagon dev`, `lagon build` or `lagon deploy`, you don't need anymore to specify the function's entrypoint and the public directory. These configuration are saved into a local `.lagon/config.json` file.
Note that `lagon dev` still allows to specify an entrypoint and public directory as before using arguments and options, making it easy to test locally.
---
That means after the first configuration asks us the path to the function's entrypoint and (optionally) the path to an assets directory, we can simply run `lagon dev` / `lagon deploy` without specifying again these settings.
=> feat(cli): improve DX by saving configuration in a local config file

.changeset/lovely-doors-brush.md, crates/cli/src/utils/deployments.rs
- Add a text about the relative path when setting up a configuration
- Show a help text about `--prod` flag when not deploying in production
=> feat(cli): improve DX by showing more information when deploying

.changeset/wise-beers-joke.md, crates/cli/src/commands/dev.rs
Previously, the server-side state wasn't kept between requests because a new isolate was recreated every time. This is no longer the case for the dev server.
The isolate is now created once when receiving an initial request and is kept in memory for subsequent requests. When the function's entry point is updated (meaning the dev server needs to reload), the isolate is cleared and a new one is recreated on the next request.
=> fix(cli): re-use the same isolate between requests to keep server-side state

.changeset/loud-mugs-arrive.md, .changeset/ten-wolves-kneel.md, crates/cli/src/commands/dev.rs, crates/cli/src/main.rs, packages/docs/pages/cli.mdx
Allow using `lagon dev` without any arguments, to use the current directory configuration (or create a new one if none is present). Also fix the `--env` option to be relative from the root.
=> fix(cli): allow `lagon dev` without arguments

.changeset/light-parents-lay.md, crates/serverless/src/deployments/pubsub.rs
The redis connection might fail sometimes and causes serverless to stop doing live deployments/undeployments. This PR adds retries to reconnect when an error from redis is returned and adds logging for connections & errors.
=> fix(serverless): reconnect Redis Pub/Sub on error

.changeset/bright-hairs-rescue.md, packages/integrations/astro/package.json
Fix regression of https://github.com/lagonapp/lagon/pull/569. Since the adapter is used in Node.js, we can bundle for Node.js using `tsup-node` that excludes all dependencies from the bundle.
=> fix(astro): bundle for Node.js by excluding all dependencies

.changeset/fair-tomatoes-unite.md, crates/cli/src/commands/deploy.rs, crates/cli/src/commands/link.rs, crates/cli/src/commands/login.rs, crates/cli/src/commands/ls.rs, crates/cli/src/commands/promote.rs, crates/cli/src/commands/rm.rs, crates/cli/src/commands/undeploy.rs, crates/cli/src/utils/config.rs, crates/cli/src/utils/deployments.rs, crates/cli/src/utils/trpc.rs
- What does this PR do?
parallele upload assets
- Add an issue number if this PR can fix or relates to an issue.
https://github.com/lagonapp/lagon/issues/607
- Add a changeset if needed with `pnpm changeset`
done
=> feat(cli): parallel upload of assets

.changeset/tame-ties-judge.md, crates/runtime_http/src/request.rs, crates/runtime_http/src/response.rs, crates/runtime_v8_utils/src/lib.rs
Improve objects creation speed from Rust -> JS, mostly noticeable on small objects. Instead of creating an object and then assigning properties, we can use [`v8::Object::New(isolate, prototype_or_null, names, values, length)`](https://v8.github.io/api/head/classv8_1_1Object.html#afdb58efc2065a4e7a012db394c302159) (`v8::Object::with_prototype_and_properties` in rusty_v8) to immediately create an object with the given properties.
This optimization is made in `Request::into_v8`, `Response::into_v8`, and `v8_headers_object`. The same can be made for Arrays by using [`v8::Array::New(isolate, elements, length)`](https://v8.github.io/api/head/classv8_1_1Array.html#a1689924b348f352fa5bc389c44f71cd6) (`v8::Array::new_with_elements` in rusty_v8).
Before, `Request::into_v8` takes ~12.5% (~74k req/s) …
=> perf(runtime): improve objects creation speed

.changeset/lucky-cows-cross.md, crates/runtime_isolate/src/lib.rs
Avoid a `panic!()` when polling promises and removing the current promise id. This could occur if the execution was stopped by V8 but not yet caught by the runtime.
=> fix(runtime): avoid thread panicking when promise id not found

.changeset/blue-colts-agree.md, crates/cli/src/utils/deployments.rs, crates/serverless/src/deployments/mod.rs
Don't skip deployment by not returning the error and instead print a warning when an asset failed to download.
=> fix(serverless): don't skip deployment when an asset failed to download

.changeset/famous-elephants-cry.md, crates/serverless/src/deployments/pubsub.rs
Regression of https://github.com/lagonapp/lagon/pull/614
Yield between each pub/sub message to allow streaming logs to axiom.
=> fix(serverless): logs not streaming to axiom

.changeset/large-rivers-cough.md, .changeset/loud-seahorses-yell.md, .changeset/swift-tables-grow.md, Cargo.lock, crates/runtime_http/src/request.rs, crates/runtime_http/src/response.rs, crates/runtime_utils/src/assets.rs, crates/runtime_v8_utils/src/lib.rs, crates/serverless/Cargo.toml, crates/serverless/src/deployments/cache.rs, crates/serverless/src/deployments/mod.rs, crates/serverless/src/deployments/pubsub.rs, crates/serverless/src/main.rs, crates/serverless/src/worker.rs
Improve performance in serverless, runtime, and cli by:
- using `DashMap` instead of `RwLock<HashMap>`
- using `HashMap::with_capacity` where possible
- using `ThreadRng` instead of creating a new `StdRng` every time
=> perf(serverless,runtime,cli): use DashMap & with_capacity where possible

.github/workflows/cd.yml
Run the CD workflow when `@lagon/cli@*` tags are pushed, and publish the artifacts to the release. Keep manual trigger to upload to GH Artifacts.
=> fix(ci): fix artifacts publishing to release

crates/serverless/src/deployments/downloader/fake.rs, crates/serverless/src/deployments/downloader/mod.rs, crates/serverless/src/deployments/downloader/s3_bucket.rs, crates/serverless/src/deployments/mod.rs, crates/serverless/src/deployments/pubsub/fake.rs, crates/serverless/src/deployments/pubsub/mod.rs, crates/serverless/src/deployments/pubsub/redis.rs, crates/serverless/src/main.rs, crates/serverless/src/serverless.rs, crates/serverless/tests/assets.rs, crates/serverless/tests/deployments.rs, crates/serverless/tests/errors.rs, crates/serverless/tests/pubsub.rs, crates/serverless/tests/requests.rs
- Replace `(PubSubMessage, String)` tuple by a new `PubSubMessage` struct, and rename the old `PubSubMessage` enum to `PubSubMessageKind`
- Remove `Clone` impl from `Downloader` and use an `Arc` instead
=> refactor(serverless): clean pubsub code

.changeset/proud-roses-allow.md, www/styles/globals.css
Add a `background-color` to the body to avoid white blank space when scrolling to the top/bottom of the page ❤️
=> fix(www): set body `background-color`

.changeset/early-elephants-repeat.md, crates/runtime_isolate/src/lib.rs
Isolates are terminated when they miss at least two heartbeats. The heartbeat missed count isn't reset to zero when a heartbeat has been successfully received: instead, the heartbeat missed count is decremented by one, allowing to safely terminate faulty isolates that are stuck in an infinite loop, and not randomly terminate isolates that just happen to be "slow"
=> fix(runtime): terminate isolates with 2 heartbeats missed

.changeset/grumpy-meals-repair.md, crates/runtime/tests/async_context.rs, crates/runtime/tests/timers.rs, packages/docs/pages/runtime-apis.mdx, packages/js-runtime/src/index.ts, packages/js-runtime/src/runtime/global/context.ts, packages/js-runtime/src/runtime/global/timers.ts
Closes https://github.com/lagonapp/lagon/issues/612
Basic tests are ported from https://github.com/tc39/proposal-async-context/blob/master/tests/async-context.test.ts
Add `AsyncLocalStorage` and `AsyncContext` APIs. The former extends the latter since they provide the same functionalities. Only a subset of Node.js's `AsyncLocalStorage` is implemented:
- `AsyncLocalStorage.prototype.getStore()`
- `AsyncLocalStorage.prototype.run(store, callback, ...args)`
This implementation is very basic and might have bugs. It also works through timers (`setTimeout()`, `setInterval()`) and microtasks (`queueMicrotask()`)
=> feat(js-runtime): async context

.changeset/smart-hotels-camp.md, crates/cli/src/commands/build.rs, crates/cli/src/commands/deploy.rs, crates/cli/src/commands/dev.rs, crates/cli/src/main.rs, crates/cli/src/utils/deployments.rs, packages/docs/pages/cli.mdx
Closes #683
Previously, only `lagon dev` allowed either files or directories containing a configuration as the first argument.
Now, `lagon deploy` and `lagon build` also work the same way, meaning you can type:
- `lagon dev/deploy/build` to use the local configuration (`.lagon/config.json`), or create a new one in the current directory
- `lagon dev/deploy/build path/to/directory` to use the configuration specified in the given path
- `lagon dev/deploy/build yourFile.ts` to not use any configuration file, making it easier to test
=> fix(cli): allow `lagon deploy` & `lagon build` to specify files

.changeset/young-shoes-explain.md, crates/cli/src/main.rs
Closes #696
Exit with code 1 instead of defaulting to 0 when an error occurs (on every command of the CLI)
=> fix(cli): exit with code 1 on error

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/wpt.yml
Use https://github.com/Swatinem/rust-cache instead of actions/cache which should improve the CI speed.
=> ci: use rust-cache

.changeset/chilly-lions-shake.md, crates/cli/npm/getBinary.js
`process.exit` calls were ignored due to this override.
=> fix(cli): returned exit code

.changeset/wise-rabbits-worry.md, packages/dashboard/lib/redis.ts, packages/dashboard/package.json, pnpm-lock.yaml
Closes #713
This PR upgrades [`redis`](https://github.com/redis/node-redis) to the latest version, which accepts a new `pingInterval` option that automatically send `PING` at the given ms interval to avoid timeouts.
=> fix(dashboard): API errors due to Redis timeouts

.changeset/dry-shrimps-hide.md, packages/dashboard/lib/trpc/tokensRouter.ts, packages/dashboard/locales/en.ts, packages/dashboard/locales/fr.ts, packages/dashboard/pages/profile.tsx
Closes #699
Add a "Copy" button to the tokens list, useful when using the [GitHub Action](https://github.com/lagonapp/github-action/) instead of authenticating and searching manually in `~/.lagon/config.json`. A success toast is displayed when copying a token.
| Before | After |
|---|---|
| ![Image](https://user-images.githubusercontent.com/43268759/227763078-881f8bd8-d413-44d2-9d6e-964d0ad6fd0a.png) | ![Screenshot 2023-04-01 at 11 01 11](https://user-images.githubusercontent.com/43268759/229276658-7f56da93-cb24-4a0c-8177-c2503af71b23.png) |
=> feat(dashboard): add a "copy" button to the tokens list

.changeset/clever-bananas-agree.md, crates/cli/src/utils/deployments.rs
Relates to https://github.com/lagonapp/lagon/issues/743
vite-plugin-ssr has the following conditions:
Since Lagon uses the browser platform to bundle using ESBuild, it tried to import the wrong file using the `browser` condition.
=> feat(cli): add `worker` import condition

.changeset/sharp-yaks-exist.md, www/lib/components/Footer.tsx, www/lib/components/StatusBadge.tsx
Fix https://twitter.com/tomlienard/status/1645462410185121793
Fetching the status using `{ next: { revalidate: 60 } }` on the server causes Vercel to create an ISR function, invoking it every minute (60 seconds) and causing abnormal bandwidth/functions usage.
This PR switch to client-side fetching to make sure the site is fully static and never use any function.
=> fix(www): client-side fetching for status badge

.changeset/quiet-days-begin.md, crates/runtime/tests/streams.rs, crates/serverless/src/deployments/mod.rs
Download deployments (index + assets) in parallel instead of sequentially: from ~15s to ~2s to download 150 deployments
=> perf(serverless): download deployments in parallel

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/wpt.yml, crates/runtime/package.json
Try https://github.com/moonrepo/setup-rust for improved caching
Also remove useless `env` in jobs because we have them globally, remove rust setup for release, use https://crates.io/crates/cargo-all-features for runtime tests
=> ci: use `moonrepo/setup-rust`

.changeset/poor-parents-fetch.md, Cargo.lock, crates/runtime_isolate/Cargo.toml, crates/runtime_isolate/src/bindings/fetch.rs, crates/serverless/Cargo.toml, crates/serverless/src/lib.rs, crates/wpt-runner/Cargo.toml, crates/wpt-runner/src/main.rs
Migrate from `lazy_static` to `once_cell`, since it has been merged to Rust'std. It's currently only available in nightly, but that will be easy to remove `once_cell::Lazy` and use `std::sync::LazyLock` instead: https://doc.rust-lang.org/stable/std/sync/struct.LazyLock.html
=> feat(runtime,serverless,wpt): use `once_cell` instead of `lazy_static`

.changeset/twenty-bears-flash.md, crates/cli/src/commands/dev.rs, crates/cli/src/main.rs, packages/docs/pages/cli.mdx, packages/docs/pages/cloud/environment-variables.mdx
Automatically load `.env` files with `lagon dev` if present in root. Specifying `--env <PATH>` (or `-e <PATH>`) will override and use the provided path.
=> feat(cli,docs): automatically load `.env` files with `lagon dev`

.changeset/popular-pigs-hide.md, crates/cli/src/commands/build.rs, crates/cli/src/commands/deploy.rs, crates/cli/src/commands/dev.rs, crates/cli/src/utils/deployments.rs, packages/docs/pages/cli.mdx, packages/docs/pages/cloud/environment-variables.mdx, packages/docs/pages/runtime-apis.mdx
Closes #786
`process.env.NODE_ENV` was always "production", even when using `lagon dev`. Now, `NODE_ENV` will be set to  "development" when using `lagon dev`, and "production" when deployed.
=> feat(cli,docs): set `process.env.NODE_ENV` to "development" when using `lagon dev`

crates/cli/src/commands/dev.rs, crates/cli/src/main.rs, packages/docs/pages/cli.mdx
Following https://github.com/lagonapp/lagon/pull/788
Add a new `--prod` (or `--production`) flag to `lagon dev` to force `process.env.NODE_ENV` to "production" instead of "development".
=> feat(cli,docs): add `--prod` to `lagon dev` to force `NODE_ENV` to "production"

.changeset/empty-brooms-drum.md, .changeset/old-gifts-remain.md, packages/dashboard/lib/pages/settings/SettingsGeneral.tsx, packages/dashboard/lib/trpc/organizationsRouter.ts, packages/ui/src/components/Text/styles.ts
- Allow creating an organization without a description
- Allow removing completely a description when updating an organization
- Fix the `Text` component to be red when using the `error` prop
=> fix(dashboard,ui): organization name/description validators

.changeset/few-gifts-confess.md, .github/workflows/release.yml
Add [NPM packages provenance](https://github.blog/2023-04-19-introducing-npm-package-provenance/) to `@lagon/cli`, `@lagon/astro` & `@lagon/remix`
=> ci: add NPM packages provenance

.changeset/shy-terms-lay.md, www/next.config.js
Using the new deployment summary from Vercel, I've noticed that www wasn't rendered as fully static:
After digging a lot and using `vercel build`, turns out that you need to specify manually `output: 'export'` when using the app dir to create a fully static website.
=> fix(www): export fully static

.changeset/honest-bears-relate.md, packages/dashboard/lib/api/functions.ts, packages/dashboard/lib/constants.ts, packages/dashboard/lib/form/validators.ts, packages/dashboard/lib/trpc/functionsRouter.ts
Closes #805
Only allow lowercase alphanumeric characters and dashes for Functions names, both when creating or when updating a Function.
=> feat(dashboard): only allow lowercase alphanumeric chars and dashes for functions names

.changeset/stupid-spies-jog.md, crates/runtime/tests/async_context.rs, crates/runtime/tests/crypto.rs, crates/runtime/tests/fetch.rs, crates/runtime/tests/runtime.rs, crates/runtime/tests/streams.rs, crates/runtime_http/src/request.rs, crates/runtime_http/src/response.rs, crates/serverless/src/main.rs, crates/wpt-runner/current-results.md, packages/js-runtime/src/__tests__/fetch.test.ts, packages/js-runtime/src/index.ts, packages/js-runtime/src/runtime/http/Request.ts, packages/js-runtime/src/runtime/http/body.ts, packages/js-runtime/src/runtime/http/fetch.ts
To avoid serializing the body of `Request` & `Response` too often, we can make it an `ArrayBuffer` and store it as-is (while transforming it when we use `Body#text()`, `Body#json()`, `Body#arrayBuffer()`). This also enables non-utf characters in body.
=> feat(runtime,js-runtime): use ArrayBuffer for Request/Response body

.changeset/smooth-walls-float.md, crates/serverless/src/deployments/mod.rs
Closes #762 
Download deployments assets in parallel instead of sequentially. From ~5s to ~3s on Lagon Cloud deployments.
=> perf(serverless): download deployments assets in parallel

.changeset/early-ants-smile.md, crates/runtime_isolate/src/lib.rs, crates/runtime_isolate/src/options.rs
`v8::GetHeapStatistics` is very expensive and we don't need to run it after each request. Instead, we calculate it at most one time per second, if a request has been made.
Take a look at `HashMap::retain` on the left:
Before:
After:
=> perf(runtime): calculate statistics at every second at most

.changeset/friendly-doors-end.md, crates/runtime/tests/runtime.rs, crates/runtime/tests/streams.rs, crates/runtime_http/src/headers.rs, crates/runtime_http/src/request.rs, crates/runtime_http/src/response.rs, crates/runtime_utils/src/assets.rs, crates/runtime_v8_utils/src/lib.rs, crates/serverless/src/serverless.rs
Reduce memory allocations of `Request` / `Response` by representing the headers using a `Vec<(String, Vec<String>)>` instead of a `HashMap<String, String>`
Looking at the difference between `Response::from_v8` & `Request::into_v8`:
Before:
After:
=> perf(runtime): improve Request/Response allocations

.changeset/rich-cobras-applaud.md, crates/cli/src/commands/dev.rs, crates/runtime_http/src/lib.rs, crates/runtime_utils/src/response.rs, crates/serverless/src/serverless.rs
Reduce heap allocations of `handle_response` by removing `Box::new` & `Box::pin`
=> perf(serverless,cli): reduce heap allocations on responses

.changeset/seven-badgers-rush.md, packages/dashboard/locales/index.ts, packages/dashboard/pages/_app.tsx
=> fix(dashboard): persist language choice

.changeset/stupid-spies-jog.md, crates/runtime/tests/fetch.rs, crates/runtime_http/src/request.rs, crates/runtime_http/src/response.rs, crates/wpt-runner/current-results.md, packages/js-runtime/src/__tests__/fetch.test.ts, packages/js-runtime/src/index.ts, packages/js-runtime/src/runtime/http/fetch.ts
Partially revert https://github.com/lagonapp/lagon/pull/807: use a string for Request/Response body as it's faster than encoding/decoding a lot inside JS-land, but keep the implementation improvements (default headers & other perf improvements)
Before:
After:
=> perf(runtime,js-runtime): revert body as ArrayBuffer

.changeset/odd-shoes-unite.md, crates/cli/src/commands/login.rs
Add a link to get the authorization code when using `lagon login`, in case the browser wasn't opened.
=> feat(cli): add link to authorization code on `lagon login`

.changeset/eleven-plants-flow.md, Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/runtime_http/Cargo.toml, crates/runtime_isolate/Cargo.toml, crates/runtime_utils/Cargo.toml, crates/serverless/Cargo.toml
Tweak release build flags to improve performance (but increases build time (for release only)).
Also upgrade hyper to latest patch.
=> perf(cli,serverless): tweak release build flags

.changeset/thin-lies-warn.md, packages/integrations/astro/src/index.ts
Write Lagon's configuration file if not present when building using the Astro integration, similar to what we did on Nitro: https://github.com/unjs/nitro/pull/996
=> feat(astro): write config if not present when building

.changeset/strange-moles-wave.md, Cargo.lock, crates/runtime/tests/crypto.rs, crates/runtime_crypto/Cargo.toml, crates/runtime_crypto/src/lib.rs, crates/runtime_crypto/src/methods/decrypt.rs, crates/runtime_crypto/src/methods/encrypt.rs, packages/docs/pages/runtime-apis.mdx
Closes https://github.com/lagonapp/lagon/issues/410
=> feat(runtime): support AES-CBC for `SubtleCrypto#encrypt` & `SubtleCrypto#decrypt`

.changeset/fair-pandas-swim.md, .changeset/nine-ghosts-shop.md, .changeset/real-flowers-peel.md, crates/serverless/src/serverless.rs, packages/dashboard/lib/components/Playground.tsx, packages/dashboard/lib/constants.ts
- Fix "Londo" -> "London" typo
- Set playground TS to ESNext & add dom.iterable
- Ingest results error to the logs
=> fix(dashboard,serverless): typo, playground types & result errors logs

.changeset/gold-falcons-tie.md, packages/js-runtime/src/runtime/global/crypto.ts
`SubtleCrypto#importKey` re-uses key data when format is `raw`
=> fix(js-runtime,cli,serverless): `SubtleCrypto#importKey` re-uses key data

.changeset/nasty-ads-buy.md, crates/runtime/tests/runtime.rs, crates/runtime_isolate/src/lib.rs, crates/runtime_isolate/src/options.rs, packages/js-runtime/src/index.ts
Allow using `export as` for the handler function, which is often generated by bundlers.
Instead of relying on setting `globalThis.handler`, the handler function is grabbed from the module's exports and passed as an argument to the `masterHandler`
=> feat(runtime): allow `export as` for handler function

.changeset/nervous-books-fetch.md, crates/runtime_utils/public/403.html, crates/runtime_utils/public/404.html, crates/runtime_utils/public/500.html, crates/runtime_utils/public/502.html
This PR adds dark-mode support for error pages. This especially fixes the readability of the error pages when shown in the playground. Previously it looked like:
=> feat(runtime_utils): add dark-mode for error pages

.changeset/lazy-bears-tap.md, packages/dashboard/lib/components/Playground.tsx
Fix setting correct monaco editor theme in playground. The editor theme was only set after changing the theme not on initial page load.
- useEffect is not called again when going back to the page again
=> fix(dashboard): use correct monaco theme

.changeset/pink-carpets-hope.md, crates/runtime/tests/crypto.rs, crates/runtime_crypto/src/lib.rs, crates/runtime_crypto/src/methods/decrypt.rs, crates/runtime_crypto/src/methods/encrypt.rs, packages/docs/pages/runtime-apis.mdx, packages/js-runtime/src/runtime/global/crypto.ts
=> feat(runtime,cli,serverless): support RSA-OAEP for `SubtleCrypto#encrypt` & `SubtleCrypto#decrypt`

docker-compose.yml
- creates the `lagon` s3 bucket on start when using minio
=> fix: create s3 bucket for minio

.changeset/moody-trees-march.md, crates/serverless/src/deployments/mod.rs
When booting/rebooting, serverless did not retrieve environment variables. They were only retrieved when a new deployment was received.
=> fix(serverless): retrieve environment variables when booting

.changeset/cyan-brooms-trade.md, crates/cli/src/commands/dev.rs
Previously, the hot reloading of the dev server when using `lagon dev` only updated after the 2nd request, instead of updating immediately in the next request.
=> fix(cli): `lagon dev` hot reload immediately

.changeset/selfish-meals-joke.md, packages/dashboard/lib/form/validators.ts, packages/dashboard/lib/pages/function/FunctionSettings.tsx
Only allow alphanumeric characters, numbers, and underscore as environment variable keys.
=> fix(dashboard): restrict environment variable keys characters

.changeset/good-meals-grow.md, crates/serverless/src/deployments/cache.rs, crates/serverless/src/serverless.rs
Partially revert https://github.com/lagonapp/lagon/pull/883 to use a hashmap for the last requests cache instead of making expensive ClickHouse queries.
=> refactor(serverless): revert cache eviction using ClickHouse selects

.changeset/breezy-cycles-glow.md, crates/runtime/tests/fetch.rs, packages/js-runtime/src/runtime/http/fetch.ts
In `fetch()`, when the body is null and the method is POST or PUT, the `content-length` header should be set to 0:
Spec: https://fetch.spec.whatwg.org/#http-network-or-cache-fetch
=> fix(js-runtime): set content-length header for POST/PUT with null body

.changeset/metal-mangos-watch.md, crates/cli/src/commands/dev.rs
Small fix to load the given environment file based on the current (or specified) directory, instead of deriving it from the root. This will also better detect automatically `.env` files when using `lagon dev path/to/folder`
=> fix(cli): load env file based on current directory

.changeset/pretty-socks-grab.md, crates/runtime_utils/src/response.rs
Fix a regression in #883 were the out bytes were always 0 for sync responses. Also improve tests to prevent future regressions.
=> fix(runtime): out bytes for sync responses

.changeset/new-insects-retire.md, Cargo.lock, crates/runtime/tests/fetch.rs, crates/runtime_http/src/response.rs, crates/runtime_isolate/Cargo.toml, crates/runtime_isolate/src/bindings/fetch.rs, crates/runtime_isolate/src/bindings/mod.rs, packages/docs/pages/runtime-apis.mdx
Replace Hyper by reqwest for `fetch()`, allowing us to remove a bunch of crappy code and easily support HTTP/2, while keeping the limits of `fetch()` calls per request and fetch recursion limit.
=> feat(runtime,docs): support HTTP/2 in `fetch()`

.changeset/nasty-weeks-lie.md, .changeset/rude-toys-wait.md, Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/utils/deployments.rs, crates/cli/src/utils/trpc.rs, crates/runtime_isolate/Cargo.toml, crates/serverless/Cargo.toml, crates/serverless/src/deployments/pubsub.rs, crates/serverless_logger/Cargo.toml, crates/serverless_pubsub/Cargo.toml, crates/serverless_pubsub/src/fake.rs, crates/serverless_pubsub/src/lib.rs, crates/serverless_pubsub/src/redis.rs
- Use rustls-tls instead of native-tls
- Try to fix redis pub/sub sometimes disconnecting and not pickup up new deployments by using the blocking version (it's in a separate thread so it's ok to block) and reconnecting on error.
=> refactor(serverless,cli): redis pub/sub & rustls-tls

.changeset/modern-moose-reflect.md, crates/cli/src/commands/dev.rs, crates/runtime_http/src/headers.rs, crates/runtime_utils/src/lib.rs, crates/runtime_utils/src/response.rs, crates/serverless/src/serverless.rs, crates/serverless/tests/requests.rs
Add a new `x-robots-tag: noindex` header to responses from preview deployments, similar to what [Vercel](https://vercel.com/docs/concepts/edge-network/headers#x-robots-tag) and [Netlify](https://docs.netlify.com/site-deploys/overview/#search-engine-indexing) do. This prevents search engines from crawling preview deployments.
=> feat(serverless): add `x-robots-tag: noindex` header to preview deployments

.changeset/poor-ants-lay.md, packages/dashboard/pages/api/trpc/[trpc].ts
Properly set session information when authenticating via a token (when using the CLI). This notably fixes the assets limit when creating a deployment from the CLI.
=> fix(dashboard): set full session with token auth

.changeset/pretty-jeans-develop.md, crates/runtime/tests/fetch.rs, packages/js-runtime/src/runtime/http/fetch.ts
Allow using `fetch()` with a `Request` and an optional `init` (that will take priority). We can still use `fetch()` using a string or `URL` and an optional `init`.
MDN: https://developer.mozilla.org/en-US/docs/Web/API/fetch
=> feat(js-runtime,serverless,cli): allow `fetch()` with a `Request`

.changeset/wicked-pears-battle.md, Cargo.lock, crates/runtime_utils/src/assets.rs, crates/serverless/Cargo.toml, crates/serverless/src/serverless.rs
- Use the `inline` feature of `dashmap` that enables `inline-more` in hashbrown
- Add a fast path in `find_assets`
- Remove the connection IP handling
=> perf(serverless): small perf wins

.changeset/itchy-chicken-count.md, crates/cli/src/commands/dev.rs
Also automatically load `.env` from the current directory if we're specifying a path that is a file:
```bash
lagon dev index.ts
lagon dev src/index.ts
lagon dev ./myproject
```
=> feat(cli): automatically load `.env` from current dir

.changeset/lazy-walls-impress.md, packages/dashboard/lib/constants.ts, packages/docs/pages/cloud/regions.mdx
Fix Bangalore region to be ap-west instead of ap-south
=> fix(dashboard,docs): bangalore region is ap-west and not ap-south

.changeset/proud-bears-sell.md, packages/dashboard/lib/pages/function/FunctionOverview.tsx, packages/dashboard/locales/en.ts, packages/dashboard/locales/fr.ts
Do not crash when cron parsing fails. Send the error and the cron expression to Sentry.
=> fix(dashboard): don't crash when cron parsing fails

.changeset/perfect-boats-divide.md, crates/cli/src/commands/dev.rs, crates/runtime/tests/allow_codegen.rs, crates/runtime/tests/async_context.rs, crates/runtime/tests/crypto.rs, crates/runtime/tests/fetch.rs, crates/runtime/tests/promises.rs, crates/runtime/tests/runtime.rs, crates/runtime/tests/timers.rs, crates/runtime/tests/utils/mod.rs, crates/runtime_http/src/lib.rs, crates/runtime_http/src/response.rs, crates/runtime_isolate/src/lib.rs, crates/runtime_utils/src/assets.rs, crates/runtime_utils/src/response.rs, crates/serverless/src/clickhouse.rs, crates/serverless/src/cronjob.rs, crates/serverless/src/serverless.rs
Reduce `clone()`ing inside serverless' request handler and replace the `handle_response` signature with a `FnOnce` (instead of `Fn`)
=> perf(serverless): reduce `clone()`ing

.changeset/lucky-mails-admire.md, Cargo.lock, crates/serverless/Cargo.toml, crates/serverless/src/main.rs
Use Jemalloc instead of the default allocator for the serverless binary. This brings the performance to +100k req/s, but we might revert it later (Deno reverted it: https://github.com/denoland/deno/pull/19187)
=> perf(serverless): use Jemalloc instead of the default allocator

.changeset/slimy-moles-jump.md, crates/runtime_utils/src/assets.rs, crates/serverless/src/deployments/mod.rs, crates/serverless/src/serverless.rs, crates/serverless_downloader/src/fake.rs, crates/serverless_downloader/src/lib.rs, crates/serverless_downloader/src/s3_bucket.rs, crates/serverless_pubsub/src/lib.rs, crates/serverless_pubsub/src/redis.rs
Avoid allocating `String` where possible and use `&str` instead
=> refactor(serverless,runtime-utils): avoid allocating `String`s

.changeset/nine-waves-grow.md, crates/cli/npm/binary-install.js, crates/cli/npm/getBinary.js, crates/cli/npm/install.js, crates/cli/npm/run.js, crates/cli/package.json, pnpm-lock.yaml
Trying to fix the binary that doesn't get updated when the cli is itself updated.
=> refactor(cli): binary install

.changeset/great-teachers-draw.md, packages/dashboard/pages/api/trpc/[trpc].ts
Use the token's selected organization when the provided id is empty.
=> fix(dashboard): correctly get the organization id when using tokens

.changeset/brown-pens-scream.md, crates/cli/src/utils/deployments.rs
On Windows, the assets path includes a `\\` delimiter instead of the expected `/` that is used when deploying, and when running `lagon dev` to return the correct asset instead of calling the function.
Example debug before:
And after:
=> fix(cli): assets path on Windows

.changeset/kind-doors-behave.md, crates/runtime/tests/errors.rs, packages/js-runtime/src/index.ts
Not returning a response would previously error with an error inside the js-runtime code, which wasn't ideal. This makes sure users get a proper error message if they forgot to return a `Response` from the `handler`
=> fix(js-runtime,cli,serverless): error when handler doesn't return a Response
