- packages/runtime/src/__tests__/url.test.ts
- packages/runtime/src/isolate/runtime.ts
- packages/runtime/src/runtime/URL.ts
- packages/types/types.d.ts
Adds support for `URL` API (https://github.com/lagonapp/serverless/issues/8)
> feat(runtime): add `URL` API

- packages/website/lib/components/Dialog/index.tsx
- packages/website/lib/components/Form/index.tsx
- packages/website/lib/pages/function/FunctionDeployments.tsx
- packages/website/lib/pages/function/FunctionSettings.tsx
- packages/website/pages/settings.tsx
Add confirmation modals on:
- Organization delete
- Functions delete
- Deployments delete
- Deployments rollback
> feat(website): add confirmation modals

- packages/website/global.d.ts
- packages/website/lib/api/deployments.ts
- packages/website/lib/pages/function/FunctionDeployments.tsx
- packages/website/pages/api/organizations/[organizationId]/functions/[functionId]/deploy.ts
- packages/website/pages/api/organizations/[organizationId]/functions/[functionId]/index.ts
- packages/website/pages/api/organizations/[organizationId]/functions/index.ts
- packages/website/prisma/migrations/20220624183652_add_triggered_and_commit_to_deployments/migration.sql
- packages/website/prisma/schema.prisma
> feat(website): style deployments page

- packages/cli/package.json
- packages/cli/src/auth/index.ts
- packages/cli/src/cli.ts
- packages/cli/src/commands/login.ts
- packages/cli/src/commands/logout.ts
- packages/cli/src/commands/undeploy.ts
- Add logged in guard to error when using commands that require to be logged in
- Add confirmation when logging out
- Fix some small type issues
> feat(cli): better auth flow

- packages/website/lib/Layout.tsx
- packages/website/lib/components/Textarea/index.tsx
- packages/website/lib/hooks/useFunctions.ts
- packages/website/lib/hooks/useOrganizations.ts
- packages/website/lib/pages/functions/FunctionsList.tsx
- packages/website/lib/utils.ts
- packages/website/pages/api/organizations/[organizationId]/index.ts
- packages/website/pages/api/organizations/index.ts
- packages/website/pages/index.tsx
- packages/website/pages/new.tsx
- packages/website/pages/settings.tsx
> feat(website): add create/delete organizations

- packages/website/lib/api/index.ts
- packages/website/lib/components/Form/index.tsx
- packages/website/lib/components/Textarea/index.tsx
- packages/website/lib/constants.ts
- packages/website/lib/form/validators.ts
- packages/website/lib/pages/function/FunctionSettings.tsx
- packages/website/lib/utils.ts
- packages/website/pages/api/organizations/[organizationId]/functions/[functionId]/index.ts
- packages/website/pages/new.tsx
- packages/website/pages/playground/[functionId].tsx
- packages/website/pages/settings.tsx
- packages/website/prisma/migrations/20220625123135_unique_functions_name/migration.sql
- packages/website/prisma/schema.prisma
Add toasts on fetch errors, with more errors from backend and more validators in frontend.
> feat(website): improve error handling

- packages/website/lib/Layout.tsx
- packages/website/lib/components/Button/index.tsx
- packages/website/lib/components/Link/index.tsx
- packages/website/lib/components/Menu/index.tsx
- packages/website/lib/components/Nav/index.tsx
- www/lib/components/Header.tsx
- www/pages/index.tsx
Set `user-select: none` on interactive elements.
> fix(website,www): disable user-select on interactive elements

- package.json
- packages/runtime/src/isolate/runtime.ts
- packages/serverless/src/__tests__/errors.test.ts
- packages/serverless/src/__tests__/misc.test.ts
- packages/serverless/src/server.ts
- pnpm-lock.yaml
- tsconfig.json
- vitest.config.ts
Closes #38
Add stacktrace to errors to `@lagon/serverless`, and more tests for when serverless throw errors.
> feat(serverless): add errors stacktrace

- packages/cli/package.json
- packages/cli/src/commands/deploy.ts
- packages/cli/src/commands/login.ts
- packages/cli/src/commands/undeploy.ts
- packages/cli/src/trpc.ts
- packages/cli/src/utils/deployments.ts
- packages/website/pages/api/trpc/[trpc].ts
- pnpm-lock.yaml
Switch to `@trpc/client` for the CLI after #40
> refactor(cli): use @trpc/client

- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/cli/src/commands/deploy.ts
- packages/cli/src/commands/dev.ts
- packages/runtime/package.json
- packages/runtime/src/isolate/index.ts
- packages/serverless/package.json
- pnpm-lock.yaml
> feat(cli): add dev command

- README.md
Italics are unclear; often = [emphasize](https://www.thesaurus.com/e/grammar/when-should-you-use-italics/)
TBH I would not list other statuses, but strikethroughs are MUCH more clear.
> fix status

- packages/cli/example-function.ts
- packages/cli/package.json
- packages/cli/src/auth/index.ts
- packages/cli/src/commands/deploy.ts
- packages/cli/src/commands/dev.ts
- packages/cli/src/commands/login.ts
- packages/cli/src/commands/logout.ts
- packages/cli/src/commands/undeploy.ts
- packages/cli/src/utils/deployments.ts
- packages/cli/src/utils/index.ts
- packages/cli/src/utils/logger.ts
- packages/website/pages/api/deployment.ts
Improve the terminal output for all commands, with more colors and spaces. Also clean duplicated code
> refactor(cli): better terminal output

- packages/cli/example-function.ts
- packages/cli/src/commands/dev.ts
- packages/cli/src/utils/index.ts
> feat(cli): support `.env` to inject env variables in locally developed functions

- packages/website/lib/components/Dialog/index.tsx
- packages/website/lib/components/Form/index.tsx
- packages/website/lib/components/TagsInput/index.tsx
- packages/website/lib/components/Text/index.tsx
- packages/website/lib/form/validators.ts
- packages/website/lib/pages/function/FunctionSettings.tsx
- packages/website/pages/profile.tsx
- packages/website/pages/settings.tsx
Improve environment variables and custom domain in function settings.
> feat(website): improve functions settings

- packages/website/pages/_app.tsx
Use stone colors and support dark mode.
> feat(website): customize toast colors

- package.json
- packages/website/lib/components/FunctionLinks.tsx
- packages/website/lib/components/Link/index.tsx
- packages/website/lib/components/Nav/index.tsx
- packages/website/lib/pages/function/FunctionDeployments.tsx
- packages/website/lib/pages/function/FunctionLogs.tsx
- packages/website/lib/pages/function/FunctionOverview.tsx
- packages/website/lib/pages/function/FunctionSettings.tsx
- packages/website/lib/pages/functions/FunctionsList.tsx
- packages/website/pages/profile.tsx
- packages/website/pages/settings.tsx
Make the website responsive. Break at `md` for everything.
> feat(website): make it responsive

- packages/website/lib/Layout.tsx
- packages/website/lib/components/FunctionLinks.tsx
- packages/website/lib/components/LayoutTitle.tsx
- packages/website/lib/hooks/useFunction.ts
- packages/website/lib/hooks/useFunctionLogs.ts
- packages/website/lib/hooks/useFunctionStats.ts
- packages/website/lib/hooks/useTokens.ts
- packages/website/lib/pages/function/FunctionDeployments.tsx
- packages/website/lib/pages/function/FunctionLogs.tsx
- packages/website/lib/pages/function/FunctionOverview.tsx
- packages/website/lib/pages/function/FunctionSettings.tsx
- packages/website/next.config.js
- packages/website/pages/_app.tsx
- packages/website/pages/api/auth/[...nextauth].ts
- packages/website/pages/cli.tsx
- packages/website/pages/functions/[functionId]/index.tsx
- packages/website/pages/index.tsx
- packages/website/pages/new.tsx
- packages/website/pages/playground/[functionId].tsx
- packages/website/pages/profile.tsx
- packages/website/pages/settings.tsx
- Use JWT tokens for sessions
- Extract layout to top-level to avoid navigation glitch/full-page rerenders
> refactor(website): improve performances

- .gitignore
- docker/nginx.Dockerfile
- docker/nginx/nginx.conf
> chore(docker): add SSL and HTTP/2 to nginx

- packages/cli/package.json
> chore(cli): bump version to 0.0.7

- packages/cli/src/cli.ts
- packages/cli/src/commands/dev.ts
> feat(cli): support specify port and host

- packages/serverless/src/master.ts
- packages/serverless/src/worker.ts
- packages/website/lib/api/deployments.ts
- packages/website/lib/trpc/deploymentsRouter.ts
- packages/website/lib/trpc/functionsRouter.ts
- Assign updated domains without redeploying the function.
> feat(website,serverless): update domains without redeploy

- packages/website/locales/en.ts
- packages/website/locales/fr.ts
- packages/website/locales/index.ts
- packages/website/next.config.js
- packages/website/package.json
- packages/website/pages/_app.tsx
- packages/website/pages/index.tsx
- packages/website/pages/profile.tsx
- packages/website/pages/settings.tsx
- pnpm-lock.yaml
Add [next-international](https://github.com/QuiiBz/next-international) for i18n
> feat(website): add next-international for i18n

- examples/react-ssr/App.tsx
- examples/react-ssr/index.tsx
- examples/react-streaming/App.tsx
- examples/react-streaming/Hello.tsx
- examples/react-streaming/index.tsx
- examples/react-streaming/package.json
- examples/react-streaming/public/main.css
- packages/cli/package.json
- packages/cli/src/commands/dev.ts
- packages/runtime/package.json
- packages/runtime/src/__tests__/base64.test.ts
- packages/runtime/src/__tests__/env.test.ts
- packages/runtime/src/__tests__/eval.test.ts
- packages/runtime/src/__tests__/fetch.test.ts
- packages/runtime/src/__tests__/isolate.test.ts
- packages/runtime/src/__tests__/logs.test.ts
- packages/runtime/src/index.ts
- packages/runtime/src/isolate/index.ts
- packages/runtime/src/isolate/runtime.ts
- packages/runtime/src/runtime/base64.ts
- packages/runtime/src/runtime/streams.ts
- packages/serverless/package.json
- packages/serverless/src/deployments/index.ts
- packages/serverless/src/server.ts
- packages/website/lib/api/deployments.ts
- packages/website/lib/trpc/functionsRouter.ts
- packages/website/pages/api/deployment.ts
- pnpm-lock.yaml
> feat(runtime,serverless): add response streaming

- .changeset/config.json
- Use `@changesets/changelog-github`
- Set `access` to public
- `ignore` all example packages
> chore(changeset): update configuration

- .changeset/shy-coins-enjoy.md
- packages/cli/src/commands/dev.ts
- packages/cli/src/utils/deployments.ts
- packages/cli/src/utils/logger.ts
Improve CLI output with bold colors, better `console.*` messages.
> refactor(cli): improve output and logs

- .changeset/old-bikes-work.md
- .changeset/strong-dryers-fold.md
- packages/cli/src/commands/dev.ts
- packages/common/src/helpers/extensions.ts
- packages/serverless/src/deployments/index.ts
- packages/serverless/src/server.ts
Correctly handle favicons from the assets in `@lagon/serverless` and `@lagon/cli`.
Also add `.ico` to extensions type in `@lagon/common`
> feat(serverless,runtime): handle favicons

- .github/workflows/ci.yml
- package.json
- packages/serverless/src/__tests__/__snapshots__/server.test.ts.snap
- packages/serverless/src/__tests__/deployments.test.ts
- packages/serverless/src/__tests__/server.test.ts
- packages/serverless/src/deployments/index.ts
- packages/serverless/src/deployments/result.ts
- pnpm-lock.yaml
Closes #89 
Add integration tests to `@lagon/serverless`
> test(serverless): add integration tests

- packages/website/locales/index.ts
- packages/website/package.json
- packages/website/pages/cli.tsx
- packages/website/pages/index.tsx
- packages/website/pages/new.tsx
- packages/website/pages/profile.tsx
- packages/website/pages/settings.tsx
- pnpm-lock.yaml
Update `next-international` to 0.2.0
> chore(website): update next-international to 0.2.0

- docker/nginx/nginx.conf
Add comments and improve SSL configuration.
> feat(docker): improve nginx config

- .changeset/honest-icons-worry.md
- packages/astro/package.json
Don't bundle `astro` inside the integration.
> fix(astro): don't bundle astro

- .changeset/two-seas-love.md
- packages/cli/src/commands/dev.ts
- packages/runtime/src/__tests__/encoding.test.ts
- packages/runtime/src/runtime/Response.ts
- packages/serverless/src/__tests__/__snapshots__/server.test.ts.snap
- packages/serverless/src/__tests__/server.test.ts
- packages/serverless/src/server.ts
Support `Uint8Array` for `Response` body.
> feat(runtime,cli,serverless): support `Uint8Array` for `Response` body

- packages/website/lib/api/deployments.ts
Just a small fix for s3 command
- Try to add a test if possible
> fix(website): s3 command doesn't use `process.env.S3_BUCKET`

- packages/rust-runtime/package.json
Set `private: true` to `rust-runtime`
> fix(runtime): rust runtime is private

- packages/rust-runtime/js/index.ts
- packages/rust-runtime/js/process.ts
- packages/rust-runtime/js/runtime.js
- packages/rust-runtime/src/isolate/mod.rs
- packages/rust-runtime/src/runtime/mod.rs
Move retrieval of runtime code and handle errors properly.
> refactor(runtime): move retrieval of runtime code

- pnpm-lock.yaml
- www/package.json
- www/pages/_app.tsx
- www/pages/index.tsx
Replace `splitbee` by `posthog` for analytics and more.
> refactor(www): replace splitbee by posthog

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- packages/cli/npm/getBinary.js
- packages/cli/npm/install.js
- packages/cli/npm/run.js
- packages/cli/npm/uninstall.js
- packages/cli/package.json
- pnpm-lock.yaml
Add publishing to NPM (using [binary-install](https://github.com/EverlastingBugstopper/binary-install)) and Crates.io.
> chore(cli): add publishing

- .github/workflows/cd.yml
Upload CLI artifacts (#148) to the current tag release.
> ci: upload CLI artifacts to tag's release

- .changeset/orange-garlics-guess.md
- packages/cli/package.json
Fix `bin` entry in `package.json`
> fix(cli): binary name

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
Add [concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency) and [Turbo Remote Caching](https://turborepo.org/docs/core-concepts/remote-caching) in the CI.
> chore(ci): add concurrency and turbo

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- packages/cli/package.json
- packages/cli/src/utils/deployments.rs
- packages/cli/src/utils/mod.rs
- packages/runtime/package.json
- packages/runtime/src/http/mod.rs
- packages/runtime/src/isolate/allocator.rs
- packages/runtime/src/isolate/bindings/fetch.rs
- packages/runtime/src/isolate/mod.rs
- packages/runtime/src/lib.rs
- packages/runtime/src/runtime/mod.rs
- packages/serverless/package.json
- packages/serverless/src/deployments/filesystem.rs
- packages/serverless/src/deployments/mod.rs
- packages/serverless/src/http/mod.rs
- packages/serverless/src/main.rs
Apply Clippy suggestions to Rust packages and run Clippy in `lint` scripts (for CI).
> refactor(cli,runtime,serverless): apply clippy suggestions

- packages/js-runtime/src/runtime/console.ts
- packages/runtime/src/http/mod.rs
- packages/runtime/src/isolate/mod.rs
- packages/runtime/src/runtime/mod.rs
- packages/runtime/tests/errors.rs
- packages/runtime/tests/promises.rs
- packages/runtime/tests/runtime.rs
- packages/serverless/src/main.rs
Clean code, fix event loop bugs and add some tests.
> refactor: clean Rust code

- Cargo.lock
- packages/runtime/src/isolate/mod.rs
- packages/serverless/Cargo.toml
- packages/serverless/src/main.rs
A thread can run multiple isolates, but an isolate can only run in the same thread.
> refactor(serverless): scope isolates to specific threads

- packages/serverless/src/main.rs
Fix Clippy error on serverless caught by the CI:
> chore(serverless): fix clippy error

- Cargo.lock
- packages/website/lib/trpc/deploymentsRouter.ts
Fix s3 is undefined error in deployments router.
> fix(website): s3 is undefined error

- .changeset/fresh-carpets-wonder.md
- .changeset/good-adults-add.md
- packages/js-runtime/src/__tests__/console.test.ts
- packages/js-runtime/src/__tests__/fetch.test.ts
- packages/js-runtime/src/index.ts
- packages/js-runtime/src/runtime/Response.ts
- packages/js-runtime/src/runtime/console.ts
- packages/js-runtime/src/runtime/fetch.ts
- packages/runtime/Cargo.toml
- packages/runtime/src/http/method.rs
- packages/runtime/src/http/mod.rs
- packages/runtime/src/http/request.rs
- packages/runtime/src/http/response.rs
- packages/runtime/src/isolate/bindings/fetch.rs
- packages/runtime/tests/errors.rs
- packages/runtime/tests/fetch.rs
- packages/runtime/tests/promises.rs
- packages/runtime/tests/runtime.rs
- packages/serverless/src/deployments/assets.rs
- packages/serverless/src/main.rs
> feat(runtime,js-runtime): complete fetch APIs

- .changeset/chatty-avocados-argue.md
- Cargo.lock
- packages/cli/Cargo.toml
- packages/cli/src/commands/dev.rs
- packages/cli/src/main.rs
- packages/serverless/src/main.rs
> feat(cli): add `lagon dev` command

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
Cache Rust artifacts in the CI/CD.
> chore(ci): cache Rust artifacts

- .changeset/khaki-doors-arrive.md
- Cargo.lock
- packages/cli/Cargo.toml
- packages/cli/src/commands/build.rs
- packages/cli/src/commands/deploy.rs
- packages/cli/src/commands/dev.rs
- packages/cli/src/utils/deployments.rs
Add live reload to the dev server of the CLI, relates to #166 (#189)
> feat(cli): add live reload to dev server

- packages/cli/npm/getBinary.js
- packages/cli/npm/install.js
- packages/cli/npm/uninstall.js
> fix(cli): add back try/catch

- .changeset/fresh-pigs-walk.md
- packages/cli/npm/run.js
- packages/cli/src/commands/dev.rs
> fix(cli): dev command

- .changeset/dull-cooks-occur.md
- .changeset/quiet-ligers-chew.md
- packages/cli/npm/getBinary.js
- packages/cli/npm/install.js
- packages/cli/npm/run.js
- packages/cli/npm/uninstall.js
- packages/cli/package.json
- packages/cli/src/main.rs
- pnpm-lock.yaml
- Show the correct version (from `package.json`) when running `--version`
- Add `update-notifier` for notifying for new release
> feat(cli): improve versioning

- .changeset/poor-laws-divide.md
- packages/js-runtime/src/runtime/streams.ts
Fix regression of https://github.com/lagonapp/lagon/pull/210
> fix(js-runtime): make streaming APIs global

- packages/runtime/tests/streams.rs
Add tests for streaming responses. Each test pulls the stream tx until it is empty.
> test(runtime): add tests for streaming

- .changeset/fluffy-jars-allow.md
- packages/runtime/src/http/mod.rs
- packages/runtime/src/isolate/mod.rs
- packages/runtime/src/runtime/mod.rs
- packages/runtime/tests/errors.rs
Throw an error when importing a module. All code should be bundled in a single file.
> feat(runtime): throw error when importing modules

- Cargo.lock
- packages/runtime/Cargo.toml
- packages/runtime/src/http/mod.rs
- packages/runtime/src/http/request.rs
- packages/runtime/src/http/response.rs
- packages/runtime/src/isolate/bindings/fetch.rs
- packages/runtime/src/isolate/bindings/mod.rs
- packages/runtime/src/isolate/mod.rs
- packages/runtime/src/lib.rs
- packages/runtime/src/runtime/mod.rs
- packages/runtime/src/utils.rs
Use anyhow for `Error` and refactor v8 utilities.
> refactor(runtime): improve error handling

- .changeset/calm-parents-live.md
- packages/serverless/public/404.html
- packages/serverless/public/500.html
- packages/serverless/public/502.html
- packages/serverless/src/main.rs
Improve 500/400 pages with proper HTML/CSS.
> feat(serverless): better 500/404 pages

- .changeset/dull-vans-hunt.md
- packages/docs/package.json
- packages/docs/pages/_app.tsx
- pnpm-lock.yaml
- www/package.json
- www/pages/_app.tsx
Add [vercel audiences](https://vercel.com/analytics) to www and docs websites.
> feat(www,docs): add vercel audiences

- .changeset/slow-eggs-return.md
- packages/cli/src/commands/build.rs
- packages/cli/src/commands/deploy.rs
- packages/cli/src/commands/dev.rs
- packages/cli/src/commands/login.rs
- packages/cli/src/commands/logout.rs
- packages/cli/src/commands/undeploy.rs
- packages/cli/src/utils/config.rs
- packages/cli/src/utils/deployments.rs
- packages/cli/src/utils/mod.rs
- packages/cli/src/utils/trpc.rs
Properly handle tRPC errors and propagate any error up to show an error message instead of panicking with `unwrap()` everywhere.
> feat(cli): handle tRPC errors

- .changeset/gentle-dodos-buy.md
- packages/js-runtime/src/__tests__/formData.test.ts
- packages/js-runtime/src/index.ts
- packages/js-runtime/src/runtime/FormData.ts
- packages/js-runtime/src/runtime/Request.ts
- packages/js-runtime/src/runtime/Response.ts
- packages/js-runtime/src/runtime/body.ts
- packages/js-runtime/src/runtime/core.ts
Add `FormData` API (similar to `URLSearchParams`), and implement `formData` method to `Request`/`Response`.
> feat(js-runtime): add FormData and multipart parsing

- .changeset/strong-zebras-camp.md
- packages/docs/pages/runtime-apis.mdx
- packages/js-runtime/package.json
- packages/js-runtime/src/index.ts
- packages/js-runtime/src/runtime/abort.ts
- packages/js-runtime/src/runtime/http/Request.ts
- packages/js-runtime/src/runtime/http/fetch.ts
- packages/runtime/tests/fetch.rs
- pnpm-lock.yaml
Closes #246 
Add `AbortController` / `AbortSignal` APIs.
> feat(js-runtime): add AbortController/AbortSignal APIs

- .changeset/clever-dots-destroy.md
- packages/serverless/src/main.rs
Add logs for error response types (error, timeout, memory).
> feat(serverless): add logs for response types

- .changeset/fast-wasps-beam.md
- Cargo.lock
- packages/cli/Cargo.toml
- packages/cli/src/commands/dev.rs
Improve `console.*` output when running `lagon dev`.
> feat(cli): improve console.* with `lagon dev`

- packages/js-runtime/src/runtime/http/Headers.ts
- packages/wpt-runner/current-results.md
- packages/wpt-runner/package.json
Improve conformance for `Headers` API with web-platform-tests. Also add a `current-results.md` file that is the output of running wpt-runner, to track changes.
> fix(js-runtime): improve Headers conformance with web-platform-tests

- .changeset/late-fans-sort.md
- packages/cli/src/commands/mod.rs
- packages/cli/src/commands/rm.rs
- packages/cli/src/main.rs
Relates to #268 
Rename `lagon undeploy` to `lagon rm`
> feat(cli): rename `lagon undeploy` to `lagon rm`

- package.json
> chore: update pnpm to 7.17.0

- examples/trpc/index.tsx
- examples/trpc/package.json
- examples/trpc/router.ts
- pnpm-lock.yaml
Add a [tRPC](https://trpc.io) example, because it's awesome.
> feat(examples): add tRPC example

- .github/renovate.json
Automerge patch instead of minor.
> fix(renovate): automerge patch instead of minor

- .changeset/old-rivers-lie.md
- .changeset/swift-seas-smash.md
- Cargo.lock
- packages/cli/Cargo.toml
- packages/cli/src/commands/deploy.rs
- packages/cli/src/commands/link.rs
- packages/cli/src/commands/ls.rs
- packages/cli/src/commands/mod.rs
- packages/cli/src/commands/promote.rs
- packages/cli/src/commands/undeploy.rs
- packages/cli/src/main.rs
- packages/cli/src/utils/trpc.rs
- packages/docs/pages/cli.mdx
Closes #268 
Add `lagon ls`, `lagon undeploy` & `lagon promote` commands.
> feat(cli): add `lagon ls`, `lagon undeploy` & `lagon promote` commands

- packages/serverless/src/deployments/mod.rs
- packages/serverless/src/deployments/pubsub.rs
Move `download` function to method inside `Deployment` struct, since it makes a lot more sense.
> refactor(serverless): move function to method inside `Deployment` struct

- .changeset/thin-seals-approve.md
- packages/dashboard/lib/trpc.ts
- packages/dashboard/pages/api/trpc/[trpc].ts
Log tRPC errors to console and clean the `createTRPCNext` method.
> refactor(dashboard): log tRPC errors to console + clean code

- .changeset/fuzzy-hairs-push.md
- packages/serverless/src/deployments/filesystem.rs
- packages/serverless/src/main.rs
Improve logs on serverless:
- Remove assets downloading logs
- Add IP to no hostname/no deployment warn logs
> feat(serverless): improve logs

- .changeset/gorgeous-timers-swim.md
- packages/ui/src/components/Form/index.tsx
- What does this PR do?
Fixes a typo. From "An error occured" -> "An error occurred".
- Add an issue number if this PR can fix or relates to an issue.
- Add a changeset if needed with `pnpm changeset`
- Try to add a test if possible
> fix: correcting grammar

- .changeset/cold-jokes-talk.md
- README.md
- packages/docs/pages/contributing.mdx
- Add an info banner about the `good first issue` label
- Add a Contributing section to the README to redirect to the documentation
- Add a section about the UI package
- Add a "Before submitting a PR" section to talk about the lint/typecheck scripts and changeset
> feat(docs): improve contributing guidelines

- .changeset/famous-flies-exercise.md
- .changeset/perfect-beers-smile.md
- .changeset/warm-frogs-share.md
- packages/dashboard/lib/api/functions.ts
- packages/dashboard/lib/pages/function/FunctionSettings.tsx
- packages/dashboard/lib/trpc/deploymentsRouter.ts
- packages/dashboard/lib/trpc/functionsRouter.ts
- packages/dashboard/lib/trpc/tokensRouter.ts
- packages/dashboard/pages/index.tsx
- packages/dashboard/pages/playground/[functionId].tsx
- Fix create function button and playground deployments
- Updating a function will only update the given fields instead of all fields
- Don't allow creating/updating functions with a non-unique name
> fix(dashboard): various issues

- packages/dashboard/lib/constants.ts
- packages/dashboard/lib/pages/function/FunctionSettings.tsx
- packages/docs/pages/cloud/regions.mdx
Add documentation for the `Regions` page. Also, update the regions inside `packages/dashboard`
> feat(docs): add regions docs

- .changeset/many-rabbits-shave.md
- packages/dashboard/package.json
- packages/dashboard/prisma/migrations/20221217074048_add_indexes/migration.sql
- packages/dashboard/prisma/schema.prisma
- pnpm-lock.yaml
- Pin Prisma version
- Add indexes to each table
- Remove `referentialIntegrity` preview feature as it is not useless
> feat(dashboard): add indexes to Prisma schema

- .github/workflows/wpt.yml
- Cargo.lock
- packages/js-runtime/src/runtime/http/Headers.ts
- packages/wpt-runner/current-results.md
- packages/wpt-runner/src/main.rs
Following https://github.com/lagonapp/lagon/pull/272
Make the CI fail when the results of web-platform-tests changes without being updated in the PR.
> ci: fail web-platform-tests when results change

- packages/js-runtime/src/runtime/http/Headers.ts
- packages/js-runtime/src/runtime/http/body.ts
- packages/runtime/src/isolate/mod.rs
- packages/wpt-runner/current-results.md
- packages/wpt-runner/src/main.rs
- Add more conformance to web-platform-tests
- Enable more tests
- Add the conformance % add the end of each run
> feat(wpt,runtime,js-runtime): more conformance

- examples/hattip/handler.ts
- examples/hattip/index.ts
- examples/hattip/package.json
- examples/hono/index.ts
- examples/hono/package.json
- examples/rakkas/package.json
- examples/rakkas/src/crud.ts
- examples/rakkas/src/routes/about.page.tsx
- examples/rakkas/src/routes/index.page.tsx
- examples/rakkas/src/routes/layout.module.css
- examples/rakkas/src/routes/layout.tsx
- examples/rakkas/src/routes/todo/Todo.module.css
- examples/rakkas/src/routes/todo/Todo.tsx
- examples/rakkas/src/routes/todo/index.page.tsx
- examples/rakkas/src/routes/todo/page.module.css
- examples/rakkas/tsconfig.json
- examples/rakkas/vite.config.ts
- pnpm-lock.yaml
Following #97, #187 
Add basic examples for [Hono](https://honojs.dev/), [HatTip](https://github.com/hattipjs/hattip), and [Rakkas](https://rakkasjs.org/).
> chore: add Hono, HatTip, Rakkas examples

- .husky/pre-commit
- package.json
- packages/astro/package.json
- packages/ui/.storybook/main.ts
- pnpm-lock.yaml
- Remove husky & lint-staged
- Remove useless mock-fs dependency
- Remove tsup and use esbuild to bundle `packages/astro`
> chore: remove husky

- .changeset/proud-bananas-exercise.md
- .changeset/shiny-rabbits-pay.md
- .changeset/wicked-houses-join.md
- Cargo.lock
- crates/runtime_isolate/src/bindings/console.rs
- crates/runtime_isolate/src/bindings/mod.rs
- crates/runtime_isolate/src/lib.rs
- crates/runtime_isolate/src/options.rs
- crates/serverless/Cargo.toml
- crates/serverless/src/cronjob.rs
- crates/serverless/src/deployments/mod.rs
- crates/serverless/src/deployments/pubsub.rs
- crates/serverless/src/main.rs
- packages/dashboard/lib/form/validators.ts
- packages/dashboard/lib/pages/function/FunctionDeployments.tsx
- packages/dashboard/lib/pages/functions/FunctionsList.tsx
- packages/dashboard/lib/trpc/functionsRouter.ts
- packages/dashboard/locales/en.ts
- packages/dashboard/locales/fr.ts
- packages/dashboard/pages/functions/[functionId].tsx
- packages/dashboard/prisma/migrations/20230116203904_update_default_cron_region/migration.sql
- packages/dashboard/prisma/schema.prisma
- packages/docs/pages/cloud/cron.mdx
Closes #262 
- Update the default region in the DB from `EU-WEST-3` to `paris-eu-west`
- WIP
> feat(serverless): support cron deployments

- .changeset/silver-beers-suffer.md
- examples/astro/package.json
- examples/astro/src/components/Card.astro
- examples/astro/src/layouts/Layout.astro
- examples/astro/src/pages/hello.astro
- examples/astro/src/pages/index.astro
- examples/astro/src/pages/prerender.astro
- packages/astro/package.json
- packages/astro/src/index.ts
- pnpm-lock.yaml
Update `@lagon/astro` integration to Astro v2. Also update the Astro example to include the new `prerender` option!
> feat(astro): update astro integration to v2

- .changeset/pink-pianos-shop.md
- .changeset/sweet-mails-admire.md
- packages/dashboard/lib/hooks/useFunction.ts
- packages/dashboard/lib/hooks/useFunctionStats.ts
- packages/dashboard/lib/hooks/useFunctionsUsage.ts
- packages/dashboard/lib/hooks/useTokens.ts
- packages/dashboard/lib/pages/function/FunctionOverview.tsx
- packages/dashboard/lib/pages/functions/FunctionsList.tsx
- packages/dashboard/lib/pages/settings/SettingsBillingUsage.tsx
- packages/dashboard/locales/en.ts
- packages/dashboard/locales/fr.ts
- packages/dashboard/pages/profile.tsx
- packages/ui/src/components/Card/index.tsx
- packages/ui/src/components/Description/index.tsx
- packages/ui/src/components/Skeleton/Skeleton.stories.tsx
- packages/ui/src/components/Skeleton/index.tsx
- Use `Suspense` in more places to allow for better loading states using `Skeleton`
- Add a new `text` variant to `Skeleton`
> feat(dashboard): improve loading states with Skeletons

- .changeset/warm-mails-nail.md
- crates/runtime_utils/public/404.html
- crates/runtime_utils/public/500.html
- crates/runtime_utils/public/502.html
- crates/serverless/src/deployments/pubsub.rs
- crates/serverless/src/main.rs
Improve 404/500/502 error pages for CLI and Serverless, with more context, and a footer link to Lagon.
> feat(cli,serverless): improve error pages

- crates/runtime/src/lib.rs
- crates/runtime_utils/src/lib.rs
- crates/runtime_utils/src/response.rs
- crates/serverless/src/cronjob.rs
- crates/serverless/src/deployments/filesystem.rs
- crates/serverless/src/deployments/mod.rs
- crates/serverless/src/main.rs
> refactor(runtime,serverless): clean code

- .changeset/bright-cherries-jump.md
- package.json
- packages/integrations/astro/package.json
- packages/integrations/remix/package.json
- pnpm-lock.yaml
- Bundle integrations (remix/astro) using [tsup](https://github.com/egoist/tsup)
- Clean unused dependencies
> feat(integrations): bundle using tsup with types

- .changeset/five-houses-pull.md
- crates/serverless/src/main.rs
Regression of https://github.com/lagonapp/lagon/pull/571
> fix(serverless): logging HTTP request

- .github/ISSUE_TEMPLATE/bug_report.md
This PR is to add the colon between field name and value for the consistency in the issue template.
> chore(docs): add colon between field name and field valaue

- Cargo.lock
- crates/cli/Cargo.toml
- crates/runtime_crypto/Cargo.toml
- crates/runtime_http/Cargo.toml
- crates/runtime_isolate/Cargo.toml
- crates/runtime_utils/Cargo.toml
- crates/runtime_v8_utils/Cargo.toml
- crates/serverless/Cargo.toml
- docker/Dockerfile
- examples/astro/package.json
- package.json
- packages/dashboard/package.json
- packages/integrations/astro/package.json
- pnpm-lock.yaml
Closes #601 
Closes #600 
Closes #599 
Closes #598 
Closes #597 
Closes #596
Closes #595 
Closes #594
> chore(deps): update deps

- packages/dashboard/lib/prisma.ts
- packages/dashboard/lib/redis.ts
- packages/dashboard/lib/s3.ts
Just fixing the NodeJS.Global type missing
> fix(dashboard): `NodeJS.Global` type missing

- .changeset/clever-hairs-stare.md
- .changeset/fair-years-sleep.md
- crates/cli/src/commands/dev.rs
- crates/runtime/tests/runtime.rs
- crates/runtime/tests/streams.rs
- crates/runtime_http/src/request.rs
- crates/runtime_http/src/response.rs
- crates/runtime_utils/src/assets.rs
- crates/runtime_v8_utils/src/lib.rs
- crates/serverless/src/main.rs
- crates/wpt-runner/current-results.md
- packages/js-runtime/src/runtime/http/Headers.ts
- Improve `getSetCookie` conformance (450 -> 456 tests passed)
- Support multiple request/response headers values
Fix https://github.com/hattipjs/hattip/pull/38 `set-cookie` test
> feat(runtime,wpt): improve headers conformance

- .changeset/curly-terms-flow.md
- www/pages/_document.tsx
Add meta `theme-color` as suggested on Twitter: https://twitter.com/belenko_me/status/1633553107941466113
> feat(www): add meta theme-color

- .changeset/wicked-kiwis-thank.md
- packages/dashboard/lib/api/functions.ts
- packages/dashboard/lib/api/organizations.ts
- packages/dashboard/lib/hooks/useOrganizationMembers.ts
- packages/dashboard/lib/pages/settings/SettingsMembers.tsx
- packages/dashboard/lib/trpc/functionsRouter.ts
- packages/dashboard/lib/trpc/organizationsRouter.ts
- packages/dashboard/lib/trpc/statsRouter.ts
- packages/dashboard/locales/en.ts
- packages/dashboard/locales/fr.ts
- packages/dashboard/prisma/migrations/20230311073514_add_organization_members/migration.sql
- packages/dashboard/prisma/schema.prisma
> feat(dashboard): add organization members

- .npmrc
- examples/nuxt/.npmrc
Try to fix https://github.com/lagonapp/lagon/actions/runs/4412883620/jobs/7733670599#step:6:121
> ci: fix Nuxi error

- .changeset/rude-suits-argue.md
- packages/dashboard/lib/pages/function/FunctionSettings.tsx
This PR aims to resolve https://github.com/lagonapp/lagon/issues/677. It's a quick-and-dirty fix so there may be a better approach.
> fix(dashboard): return normalised value if it exists

- .changeset/flat-bikes-enjoy.md
- packages/dashboard/lib/pages/function/FunctionDeployments.tsx
Closes #695
The returned date is UTC, and `Date.prototype.toLocaleString()` already format based on the user's timezone.
> fix(dashboard): deployments creation date

- .changeset/fresh-news-ring.md
- packages/dashboard/global.d.ts
- packages/dashboard/lib/Layout.tsx
- packages/dashboard/lib/api/deployments.ts
- packages/dashboard/lib/api/functions.ts
- packages/dashboard/lib/api/organizations.ts
- packages/dashboard/lib/pages/settings/SettingsBillingUsage.tsx
- packages/dashboard/lib/pages/settings/SettingsGeneral.tsx
- packages/dashboard/lib/pages/settings/SettingsMembers.tsx
- packages/dashboard/lib/trpc/deploymentsRouter.ts
- packages/dashboard/lib/trpc/functionsRouter.ts
- packages/dashboard/lib/trpc/organizationsRouter.ts
- packages/dashboard/lib/trpc/statsRouter.ts
- packages/dashboard/locales/en.ts
- packages/dashboard/locales/fr.ts
- packages/dashboard/pages/api/auth/[...nextauth].ts
- packages/dashboard/pages/api/trpc/[trpc].ts
Fix many bugs / missing implementations in Organization Members.
> fix(dashboard): Organization Members bugs

- .github/workflows/release.yml
- package.json
- Use the PAT when checking the repo for the release
- Only build `@lagon/astro` & `@lagon/remix` in the release command
> chore: fix release workflow

- .changeset/violet-books-breathe.md
- packages/dashboard/package.json
- packages/dashboard/prisma/schema.prisma
- pnpm-lock.yaml
Use Prisma `jsonProtocol` & update to the latest version.
See https://www.prisma.io/blog/prisma-and-serverless-73hbgKnZ6t
> perf(dashboard): use Prisma `jsonProtocol`

- .changeset/violet-books-breathe.md
- packages/dashboard/package.json
- packages/dashboard/prisma/schema.prisma
- pnpm-lock.yaml
> Revert "perf(dashboard): use Prisma `jsonProtocol`" (#783

- .changeset/violet-books-breathe.md
- packages/dashboard/package.json
- packages/dashboard/prisma/schema.prisma
- pnpm-lock.yaml
> Revert "Revert "perf(dashboard): use Prisma `jsonProtocol`"" (#785

- .changeset/gold-gorillas-learn.md
- .changeset/nine-hounds-smile.md
- .changeset/tricky-baboons-divide.md
- packages/dashboard/lib/components/Playground.tsx
- packages/ui/src/components/Button/styles.ts
- packages/ui/src/components/Card/styles.ts
- packages/ui/src/components/Menu/index.tsx
- packages/ui/src/styles/globals.css
- Fix playground editor theme to match the user's theme, even when updating the current theme
- Add a background color (fix macos overscroll)
- Remove shadows on dark mode
> fix(dashboard,ui): design bugs

- .changeset/wet-ladybugs-pretend.md
- examples/planetscale/index.ts
- examples/turso/.env.example
- examples/turso/index.ts
- examples/turso/package.json
- packages/docs/pages/examples.md
- pnpm-lock.yaml
Add an example of a simple SQLite query using [Turso](https://chiselstrike.com/).
> feat(docs,examples): add Turso examples

- .changeset/odd-beers-hide.md
- examples/xata/.gitignore
- examples/xata/index.ts
- examples/xata/package.json
- packages/docs/pages/examples.md
- pnpm-lock.yaml
Add an example of using [Xata](https://xata.io/) in Lagon runtime.
> feat(examples): add Xata example

- .changeset/funny-waves-confess.md
- .changeset/great-cars-design.md
- .changeset/tame-planets-wave.md
- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/commands/build.rs
- crates/cli/src/commands/deploy.rs
- crates/cli/src/commands/dev.rs
- crates/cli/src/commands/link.rs
- crates/cli/src/commands/login.rs
- crates/cli/src/commands/logout.rs
- crates/cli/src/commands/ls.rs
- crates/cli/src/commands/promote.rs
- crates/cli/src/commands/rm.rs
- crates/cli/src/commands/undeploy.rs
- crates/cli/src/main.rs
- crates/cli/src/utils/console.rs
- crates/cli/src/utils/deployments.rs
- crates/cli/src/utils/mod.rs
- crates/cli/src/utils/trpc.rs
- crates/runtime_http/src/lib.rs
- crates/runtime_http/src/request.rs
- crates/runtime_http/src/response.rs
- crates/wpt-runner/Cargo.toml
- crates/wpt-runner/src/main.rs
- Introduce a brand new design
- Pre-select confirmation inputs
- Show file errors instead of exiting immediately
> feat(cli): design & UX overhaul

- .changeset/olive-apples-wink.md
- .changeset/perfect-shirts-taste.md
- packages/dashboard/lib/components/Layout.tsx
- packages/dashboard/lib/pages/functions/FunctionsList.tsx
- packages/dashboard/pages/_app.tsx
- packages/ui/package.json
- packages/ui/src/components/Card/index.tsx
- pnpm-lock.yaml
- Do not preload Functions when hovering cards in the list
- Add an external icon next to "Documentation" in the header
> feat(dashboard): do not preload Functions on hover

- .changeset/thick-moose-attend.md
- packages/dashboard/lib/pages/function/FunctionSettings.tsx
- packages/dashboard/prisma/migrations/20230511153450_set_env_variables_max_length/migration.sql
- packages/dashboard/prisma/migrations/20230511154938_set_org_name_description_length/migration.sql
- packages/dashboard/prisma/schema.prisma
Fix environment variables' max length
> fix(dashboard): environment variable's max length

- Cargo.lock
- crates/runtime/Cargo.toml
- crates/runtime_crypto/Cargo.toml
- crates/runtime_crypto/src/methods/derive_bits.rs
- crates/runtime_http/Cargo.toml
- crates/runtime_isolate/Cargo.toml
- crates/runtime_v8_utils/Cargo.toml
- crates/serverless/Cargo.toml
- package.json
- packages/dashboard/package.json
- packages/docs/package.json
- pnpm-lock.yaml
Closes #804
Closes #852
Closes #842
Closes #850
Closes #849
Closes #846
Closes #843
Closes #841
> chore: update deps

- .changeset/mighty-hairs-tease.md
- crates/runtime/tests/crypto.rs
- crates/runtime_isolate/src/bindings/crypto/random_values.rs
- packages/js-runtime/src/index.ts
- packages/js-runtime/src/runtime/global/crypto.ts
`crypto#getRandomValues` should update the given array in-place and return it
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues
> fix(runtime,cli,serverless): `crypto#getRandomValues` updates array in-place

- crates/runtime/tests/crypto.rs
- crates/runtime_http/src/lib.rs
- packages/js-runtime/src/runtime/global/crypto.ts
Following https://github.com/lagonapp/lagon/pull/860 which broke some crypto tests
> fix(runtime): `SubtleCrypto#importKey` implementation

- .changeset/seven-doors-help.md
- packages/dashboard/lib/pages/function/FunctionSettings.tsx
Remove required validator on environment variable key & value that blocked deletion & validation
> fix(dashboard): environment variables deletion

- .changeset/chatty-pumpkins-vanish.md
- packages/dashboard/lib/api/organizations.ts
- packages/dashboard/lib/form/validators.ts
- packages/dashboard/lib/pages/function/FunctionDeployments.tsx
- packages/dashboard/lib/pages/function/FunctionSettings.tsx
- packages/dashboard/lib/pages/settings/SettingsGeneral.tsx
- packages/dashboard/lib/pages/settings/SettingsMembers.tsx
- packages/dashboard/pages/profile.tsx
- packages/ui/src/components/Dialog/Dialog.stories.tsx
- packages/ui/src/components/Dialog/index.tsx
- packages/ui/src/components/Form/index.tsx
Close dialog when submitting the form. Also simplifies the way `Dialog` works by always embedding a `Form` inside.
> fix(dashboard,ui): close dialog on submit without errors

- .changeset/hungry-geckos-tap.md
- .changeset/lemon-ducks-learn.md
- .changeset/neat-otters-live.md
- crates/cli/src/utils/console.rs
- crates/serverless/src/clickhouse.rs
- packages/dashboard/lib/pages/function/FunctionSettings.tsx
- packages/dashboard/locales/en.ts
- packages/dashboard/locales/fr.ts
- Reduce loader animation to tick every 50ms instead of 10ms in the CLI
- Fix time-to-live for logs table in ClickHouse
- Fix domains status when proxied through Cloudflare:
Before:
After:
> fix(dashboard,cli,serverless): various small bugs

- .changeset/two-lies-warn.md
- packages/dashboard/lib/api/deployments.ts
> fix(dashboard): delete env variables before deleting Function

- .changeset/curvy-beans-divide.md
- packages/dashboard/lib/pages/function/FunctionSettings.tsx
Use the form's value to show a preview of how often the Cron will be triggered as we type.
> fix(dashboard): cron preview to update as we type

- .changeset/shy-pears-film.md
- www/lib/components/Header.tsx
- Decreased nav gap for smaller screens
> fix(www): decrease nav gap on smaller screens

- .changeset/khaki-dogs-type.md
- packages/dashboard/lib/pages/function/FunctionSettings.tsx
- packages/dashboard/locales/en.ts
- packages/dashboard/locales/fr.ts
- packages/dashboard/package.json
- pnpm-lock.yaml
Correctly resolve if the domain is proxied behind Cloudflare and display proper error messages:
Before:
After:
> feat(dashboard): improve domains status

- .changeset/large-pets-rule.md
- packages/dashboard/prisma/migrations/20230602061526_remove_assets_table_use_json_instead/migration.sql
Fix wrong Prisma migration file due to a missing `;`
> fix(dashboard): wrong Prisma migration

- .changeset/cold-parents-tap.md
- .changeset/shy-comics-do.md
- examples/drizzle-turso/.env.example
- examples/drizzle-turso/drizzle.config.ts
- examples/drizzle-turso/index.ts
- examples/drizzle-turso/migrations/0000_furry_sphinx.sql
- examples/drizzle-turso/migrations/meta/0000_snapshot.json
- examples/drizzle-turso/migrations/meta/_journal.json
- examples/drizzle-turso/package.json
- examples/drizzle-turso/schema.ts
- examples/turso/index.ts
- examples/turso/package.json
- packages/docs/pages/examples.md
- pnpm-lock.yaml
Add a new Drizzle + Turso example with typesafe schema, migrations, sql-like syntax and relational queries
> chore(examples): add Drizzle + Turso example

- .changeset/metal-panthers-boil.md
- packages/dashboard/lib/api/deployments.ts
- packages/dashboard/pages/api/webhooks/stripe.ts
Upgrade functions limits on plan change, specifically the tick and total timeouts of every function in the organization. Then, we manually force a re-deploy of the production deployments of these functions.
> fix(dashboard): upgrade functions limits on plan change

- .changeset/curvy-pumas-clean.md
- crates/cli/src/commands/deploy.rs
- crates/cli/src/commands/link.rs
- crates/cli/src/commands/ls.rs
- crates/cli/src/commands/promote.rs
- crates/cli/src/commands/rm.rs
- crates/cli/src/commands/undeploy.rs
- crates/cli/src/utils/deployments.rs
- crates/cli/src/utils/trpc.rs
- packages/dashboard/pages/api/trpc/[trpc].ts
Deploy to the specified organization instead of the currently selected one.
> fix(dashboard,cli): deploy to the selected organization id

- .changeset/healthy-rats-give.md
- packages/dashboard/lib/components/Footer.tsx
- packages/dashboard/lib/components/StatusBadge.tsx
> feat(dashboard): add status badge in footer

- .changeset/shiny-plums-yell.md
- crates/serverless/src/deployments/pubsub.rs
- pnpm-lock.yaml
Always try to remove Cron functions when undeploying a Function.
> fix(serverless): properly remove Cron functions

- .changeset/calm-points-jump.md
- .gitignore
- Cargo.lock
- crates/runtime/Cargo.toml
- crates/runtime_crypto/Cargo.toml
- crates/runtime_http/Cargo.toml
- crates/runtime_isolate/Cargo.toml
- crates/runtime_v8_utils/Cargo.toml
- docker/Dockerfile.dashboard
- docker/Dockerfile.serverless
- package.json
- packages/dashboard/lib/api/organizations.ts
- packages/dashboard/lib/pages/function/FunctionDeployments.tsx
- packages/dashboard/package.json
- packages/integrations/astro/src/index.ts
- packages/integrations/remix/src/handler.ts
- packages/js-runtime/src/runtime/encoding/TextEncoder.ts
- packages/js-runtime/src/runtime/global/file.ts
- packages/js-runtime/src/runtime/http/FormData.ts
- packages/js-runtime/src/runtime/http/Headers.ts
- packages/js-runtime/src/runtime/http/URL.ts
- packages/js-runtime/src/runtime/http/URLSearchParams.ts
- packages/ui/package.json
- packages/ui/src/components/Form/index.tsx
- pnpm-lock.yaml
- www/package.json
Un-comment organization members check, and update deps:
Closes #1047
Closes #1046
Closes #1045
Closes #1044
Closes #1043
Closes #1042
> fix(dashboard): organization members check
